### ISSUE TITLE
Deploy cfn-guard-lambda via CloudFormation

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-guard#10]
Having the lambda packaged in a (SAM) template will be an easier way to deploy cfn-guard for CloudFormation users. The sam cli could be leveraged to execute the Makefile automatically (https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html).

**Comment by nathanataws** [comment]
Fair point.  We'll take a look at adding it to the roadmap. :-)
