### ISSUE TITLE
[Enhancement] Support non-alphanum properties in property paths

### ISSUE THREAD

**Issue by seawildau** [aws-cloudformation/cloudformation-guard#103]
**Is your feature request related to a problem? Please describe.**

Property paths are currently defined as alphanumeric, and rules are validated based on this definition. Some nested properties support keys that are not alphanumeric, such as IAM policy condition keys (e.g. "aws:SourceVpce", "aws:PrincipalOrgId", etc.). I want to be able to write rules that reference these nested properties, e.g.

`AWS::ApiGateway::RestApi Policy.Statement.*.Condition.StringEquals.aws:SourceVpce == /vpce-.+/`

**Describe the solution you'd like**

First class support for checking properties that aren't alphanumeric.

**Describe alternatives you've considered**

Awkward regexes on the parent key.

**Comment by jotompki** [comment]
Looks like we'd need to change the regex here:
https://github.com/aws-cloudformation/cloudformation-guard/blob/5286412d50d49ca69c725109f7c3c6e1b817e9e6/cfn-guard/src/parser.rs#L20

to support more types than just words. Will test around with this and find a better regex. Ideally we need to move to a more sophisticated solution than regex matching but will see if there's a quick fix.

**Comment by dchakrav-github** [comment]
With Guard 2.0 you can quote keys to accommodate any special characters including `.`

```
AWS::ApiGateway::RestApi Properties.Policy.Statement.*.Condition.StringEquals.'aws:SourceVpce' == /vpce-.+/
```
Remember that you need `Properties` prefix.
