### ISSUE TITLE
[BUG] It doesn't work properly for alpine

### ISSUE THREAD

**Issue by sophanith2020** [aws-cloudformation/cloudformation-guard#106]
**Describe the bug**

It doesn't work properly for alpine, sometime we can run normal and sometimes it shows the error as screenshot below

**Screenshots**

![image](https://user-images.githubusercontent.com/68974451/103326180-b56d2e00-4a81-11eb-9bd0-cac0b18368c5.png)

**Operating System:**
[Alpine]

**Comment by jotompki** [comment]
Will look into vending an alpine compatible version. Are you running from a pre built binary or installing from source? Alternatively, try running `cargo install cfn-guard` to build and install from crates.io

**Comment by sophanith2020** [comment]
@jotompki we are using from pre-built binary

**Comment by jotompki** [comment]
Closing as we recommend users to install via cargo to an installation tailored to the specific flavor of OS
