### ISSUE TITLE
[BUG] WHEN CHECK should check only the item matching WHEN condition.

### ISSUE THREAD

**Issue by helenxh** [aws-cloudformation/cloudformation-guard#107]
**Describe the bug**
I was trying to create a rule : don’t allow * in resource when action related to data and key. (For example, dynamodb:GetItem, secretsmanager:GetSecretValue)

In my test cfn template, there are a few statements within one policy, one statement contains dynamodb:GetItem and specifies the table name as resource. Another statement contains other actions and specified * in resource.

Then it failed the cfn-guard check.

**To Reproduce**
Please supply:

1. An example rule set and template that results in the error
Here is the rule, file named as test_rules
```
AWS::IAM::Policy WHEN PolicyDocument.Statement.*.Action == /.*dynamodb:GetItem.*|.*secretsmanager:GetSecretValue.*/ CHECK PolicyDocument.Statement.*.Resource != *
AWS::IAM::ManagedPolicy WHEN PolicyDocument.Statement.*.Action == /.*dynamodb:GetItem.*|.*secretsmanager:GetSecretValue.*/ CHECK PolicyDocument.Statement.*.Resource != *
```

the cfn template, github_sample.json
```
{
  "Resources": {
    "TestPolicy": {
      "Type": "AWS::IAM::ManagedPolicy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Action": [
                "dynamodb:GetItem",
              ],
              "Condition": {
                "Bool": {
                  "aws:SecureTransport": "true"
                }
              },
              "Effect": "Allow",
              "Resource": [
                "arn:aws:dynamodb:*:*:table/TestTable"
              ]
            },
            {
              "Action": [
                "acm-pca:GetCertificate"
              ],
              "Effect": "Allow",
              "Resource": "*"
            },
            {
              "Action": "logs:PutLogEvents",
              "Effect": "Allow",
              "Resource": "*"
            }
          ],
          "Version": "2012-10-17"
        },
        "Description": "",
        "ManagedPolicyName": "TestPolicy",
        "Path": "/",
        "Roles": [
          {
            "Ref": "TestRole"
          }
        ]
      },
      "Metadata": {
        "aws:cdk:path": "TestPolicy/Resource"
      }
    }
  }
}
```
1. The commands you used to invoke the tool
```
cfn-guard check -t github_sample.json -r test_rules
```

1. The output of a `-vvv` log level if it's not related to cfn-guard-lambda, or the relevant CloudWatch log messages if it is related to the lambda
the cfn template failed the check.
```
[TestPolicy] failed because [PolicyDocument.Statement.1.Resource] is [*] and that value is not permitted when AWS::IAM::ManagedPolicy PolicyDocument.Statement.*.Action == /.*dynamodb:GetItem.*|.*secretsmanager:GetSecretValue.*/
[TestPolicy] failed because [PolicyDocument.Statement.2.Resource] is [*] and that value is not permitted when AWS::IAM::ManagedPolicy PolicyDocument.Statement.*.Action == /.*dynamodb:GetItem.*|.*secretsmanager:GetSecretValue.*/
Number of failures: 2
```

**NOTE: Please be sure that the templates, rule sets and logs you provide as part of your bug report do not contain any sensitive information.**

**Expected behavior**
cfn guard should check resource for the specified statement (which met the WHEN condition), not every statement.
If I should use another way to write the rule, any suggestion is appreciated. Thanks.

**Screenshots**

**Operating System:**
[eg, MacOS, Windows, Ubuntu, etc]

**OS Version**
[eg Catalina, 10, 18.04, etc]

**Additional context**

**Comment by jotompki** [comment]
I think the issue here is that  when check filters on a resource level, not a statement level. Because of this, the when clause is satisfied for the resource "TestPolicy" because one of its statements is dynamoDb:GetItem. Then it checks the list contents for any statement under that resource because that condition is satisfied. 

If another ManagedPolicy resource existed which did not have any statements that satisfied the action regex above, they would not be checked.

I think this issue is really requesting filtering beyond the resource type filtering provided by when check. Currently it only filters down to a single resource type and cannot filter down more than that into specific PolicyDocument statements.

**Comment by helenxh** [comment]
Hello John, 

Thanks. I think so. At least that's how I understand the rule syntax. 
It's kind of limitation that we may not be able to write certain rules. So some of my team's security requirement won't be able to implemented with cfn-guard rule. Is there any walk around way? Thanks.

**Comment by jotompki** [comment]
@helenxh should be able to address this in #115 via filtering.
See the "Insufficient Property Access" section to see how exactly this will be modeled in the new rules language.

**Comment by helenxh** [comment]
Thanks John.
Looking forward to it. Then I will test it out and let you know. Thanks.

**Comment by dchakrav-github** [comment]
With 2.0 release here is guard rule 
```
# 
# Select all Managed Policies in the template
# 
let policies = Resources.*[ 
    Type == 'AWS::IAM::ManagedPolicy' 
]

rule disallows_dynamo_db_any_resource when %policies !EMPTY {
    #
    # Select all statements where the action matches GetItem or GetSecretValue
    #
    let statements = %policies.Properties.PolicyDocument.Statement[
        Action == /.*dynamodb:GetItem.*|.*secretsmanager:GetSecretValue.*/
    ]

    #
    # If there are such statements, ensure that the Resource != '*'  
    # for these
    #
    when %statements !EMPTY {
        %statements.Resource != '*'
    }
}
```

Sample run
```
cfn-guard validate -r iam.guard -d resources.json 
Summary Report Overall File Status = PASS
PASS/SKIP rules
disallows_dynamo_db_any_resource    [PASS]
```




[iam.zip](https://github.com/aws-cloudformation/cloudformation-guard/files/6505788/iam.zip)
