### ISSUE TITLE
Add option to accept piped input in --rules and --data parameters in addition to file paths

### ISSUE THREAD

**Issue by sfarazkazmi** [aws-cloudformation/cloudformation-guard#118]
Currently we accept only file or directory path in --rules and --data parameters. We want to run cfn-guard binary as part of python/java based AWS Lambda and without the option to pass string/piped values as parameters, we will have to write rules and data files in the lambda /tmp directory which gets reused as lambda reuse containers during subsequent executions.

/tmp has limited memory and we may run out of space during burst traffic.

**Comment by sfarazkazmi** [comment]
Adding string will limit us to stay within max argument length which is 2.5mb in most linux systems. We likely want capability to pipe large data into the tool instead 

Our usecase have data size of up-to 15mb.

**Comment by dchakrav-github** [comment]
With 2.0 you can stream the data via STDIN for Guard to evaluate. Guard checks need the entire document in memory to evaluate. The data will be held in memory for the duration of the evaluation and dropped after. You can only pipe in data to Guard not rules. What is the use case pipe rules as well?

**Comment by sfarazkazmi** [comment]
We want to run binary in lambda as a subprocess and without piped/stdin for rules, we will have to write files in lambda local storage. Lambda could timeout or have some other issue before we cleanup the files and since lambda reuses containers, it is possible the local storage gets full of stale files.
