### ISSUE TITLE
[Enhancement] Ability to support AWS SDK calls for enhanced checks

### ISSUE THREAD

**Issue by 0xjjoyy** [aws-cloudformation/cloudformation-guard#121]
**Is your feature request related to a problem? Please describe.**
For IAM policies, would like the ability to perform enhanced checks over the effective permissions.

**Describe the solution you'd like**
Ability to support AWS SDK calls for enhanced checks. For example, ability to invoke Access Analyzer [CreateAccessPreview](https://docs.aws.amazon.com/access-analyzer/latest/APIReference/API_CreateAccessPreview.html) for resource based policies.

**Describe alternatives you've considered**

**Additional context**

**Comment by PatMyron** [comment]
think AWS API calls in rules might be a better fit in other CloudFormation static analysis tooling described in https://github.com/aws-cloudformation/cloudformation-guard/issues/9#issuecomment-726299482 where rules are written in a language like Python/Ruby

**Comment by razcloud** [comment]
This feature is out of scope for Guard.  Closing as won't fix.
