### ISSUE TITLE
[BUG] CloudFormation Guard not working on RHEL release 7.9

### ISSUE THREAD

**Issue by gerwin90** [aws-cloudformation/cloudformation-guard#125]
Following the instructions for installation for Linux I am unable to get CloudFormation Guard running on RHEL 7. 

I have done the following:
      wget https://github.com/aws-cloudformation/cloudformation-guard/releases/download/1.0.0/cfn-guard-linux-1.0.0.tar.gz
      tar -xvf cfn-guard-linux-1.0.0.tar.gz
      cd ./cfn-guard-linux

But when I try do run CFN guard I am getting the following:
./cfn-guard-linux/
./cfn-guard-linux/cfn-guard
./cfn-guard-linux/README.md
./cfn-guard-linux/ATTRIBUTION
./cfn-guard-linux/LICENSE
./cfn-guard-linux/NOTICE
./cfn-guard: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./cfn-guard)

Have I missed the installation of a dependency?

**Comment by jotompki** [comment]
Have had some issues related to this. I would advise installing via cargo/crates for a build guaranteed to work on your machine.
```
cargo install cfn-guard
```

**Comment by gerwin90** [comment]
OK I will give this a try and see how it works out. 

Just an FYI and a slightly weird one but the CENTOS release does work on the RHEL and has no dependency issues....

**Comment by shreyasdamle** [comment]
@gerwin90 we tried installing cfn-guard v2 on RHEL release 7.9 and we didn't find any issues. Please let us know if you are still observing this issue on your end. Thanks!

**Comment by razcloud** [comment]
Closing issue as the team did not experience the same issues with cfn-guard v2 on RHEL 7.9.
