### ISSUE TITLE
Release Best Practices Rules 

### ISSUE THREAD

**Issue by K-Stefan** [aws-cloudformation/cloudformation-guard#13]
I think it is a lot of effort to write custom rules set and even you will miss some best practices or security settings. 

I really looking forward that AWS releases a set of best practices and security-relevant rules sets, for example
* Encryption of all data at rest
* well-architected rules
* RDS not started in a single AZ

For many of these best practices, AWS has already services in place which check these rules after or during deployment like Trusted Advisor and AWS Config. My hope AWS use their knowledge to transfer these into rules, so we as the customer can validate our template before we deploy Cloudformation stacks.

**Comment by ikben** [comment]
This could be related ot https://github.com/aws-cloudformation/cloudformation-guard/issues/8

**Comment by nathanataws** [comment]
@ikben is correct.  We're looking to do something along these lines as part of issue #8.

I'm going to close this ticket for now, but please do add comments to #8 on what you'd like to see.

**Comment by matthewdfuller** [comment]
@ikben - FWIW, I started a [draft PR](https://github.com/aws-cloudformation/cloudformation-guard/pull/21) that may cover your use case here. Still a WIP, but has about 35 rules directly related to these issues.

**Comment by ikben** [comment]
Thanks, @matthewdfuller looks awesome! Tagging in @K-Stefan, since he opened the issue originally

**Comment by K-Stefan** [comment]
> Thanks, @matthewdfuller looks awesome! Tagging in @K-Stefan, since he opened the issue originally

This is truly a starting point. My Request is beyond sample rules, it really about best practices and security-related rules of 'all' services.
