### ISSUE TITLE
[Enhancement] Flip installation instructions to prefer binaries

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-guard#131]
When installing CloudFormation guard, I prefer using binaries instead of installing the rust toolchain (either with brew or from the GitHub releases)

The readme does list pre-built binaries, but only after giving instructions of how to build from source. Flipping the order here, might make it easier for people to find the binaries, and get started using Guard.

**Comment by dchakrav-github** [comment]
Closing  this issue as this has been addressed with the merged push. Re-open this issue @benbridts if you still see updates that are needed
