### ISSUE TITLE
Enhancement(Unit Tests): Add Test Names To Test YAML & Adjust Console Output

### ISSUE THREAD

**Issue by AjkayAlan** [aws-cloudformation/cloudformation-guard#133]
Good Afternoon!

First of all, I wanted to thank you for the improvements in v2 - they are significant, and improve the viability of me using cfn-guard significantly.

## Background

I have a lot of unit tests for a particular guard ruleset. For example, I have a guard ruleset which checks all S3 bucket configuration for some standard things (e.g. Encryption, Logging, etc.).

I have the unit tests written to test each of the rules, requiring me to add assertions for every rule for each of the tests I have. Because I want to unit test, I would like to adjust some cases. For example, I want to see what happens when I use KMS for encryption, and what happens when I use AES256 for encryption.

This results in me having 5-6 tests for the ruleset, which has 5-6 checks

## The Problem

If I screw something up, its really hard for me to pinpoint what unit test fails based on the console output. I get console output similar to the following:

```
PASS Expected Rule = check_s3_bucket_is_encrypted, Status = SKIP, Got Status = SKIP
PASS Expected Rule = check_s3_bucket_is_logging, Status = SKIP, Got Status = SKIP
PASS Expected Rule = check_s3_bucket_is_private, Status = SKIP, Got Status = SKIP
PASS Expected Rule = check_s3_bucket_is_encrypted, Status = SKIP, Got Status = SKIP
PASS Expected Rule = check_s3_bucket_is_logging, Status = SKIP, Got Status = SKIP
PASS Expected Rule = check_s3_bucket_is_private, Status = SKIP, Got Status = SKIP
PASS Expected Rule = check_s3_bucket_is_encrypted, Status = FAIL, Got Status = FAIL
FAILED Expected Rule = check_s3_bucket_is_logging, Status = PASS, Got Status = FAIL
PASS Expected Rule = check_s3_bucket_is_private, Status = FAIL, Got Status = FAIL
PASS Expected Rule = check_s3_bucket_is_encrypted, Status = PASS, Got Status = PASS
PASS Expected Rule = check_s3_bucket_is_logging, Status = PASS, Got Status = PASS
PASS Expected Rule = check_s3_bucket_is_private, Status = PASS, Got Status = PASS
```

This has no great way to correlate to one of my tests, besides me just counting my "checks", and going to the n-th occurrence.

## The Fix

Allow me to define a `name` attribute in the YAML which is output in the tests in some way. So, for example, with the following test, I would provide a name

```
- name: Blank S3 Bucket Fails All Checks
  input:
    Resources:
      S3Bucket:
        Type: AWS::S3::Bucket
        Name: AS3Bucket
  expectations:
    rules:
      check_s3_bucket_is_encrypted: FAIL
      check_s3_bucket_is_logging: PASS
      check_s3_bucket_is_private: FAIL
```

And the output in the terminal could look something like:
```
Test: Blank S3 Bucket Fails All Checks
PASS Expected Rule = check_s3_bucket_is_encrypted, Status = FAIL, Got Status = FAIL
FAILED Expected Rule = check_s3_bucket_is_logging, Status = PASS, Got Status = FAIL
PASS Expected Rule = check_s3_bucket_is_private, Status = FAIL, Got Status = FAIL
```

This would help me quickly debug and resolve problems.

**Comment by dchakrav-github** [comment]
Thank you for the feedback. This is good enhancement request. Will put this on the backlog

**Comment by dchakrav-github** [comment]
@AjkayAlan we added this functionality. Will close this once we do finish the next release. You are welcome to clone and try it in the meantime. Thanks

**Comment by gandhek** [comment]
We have released this feature to homebrew and cargo. Closing this issue, please feel free to reach out in case on any questions.
