### ISSUE TITLE
Support numeric comparison operators

### ISSUE THREAD

**Issue by toricls** [aws-cloudformation/cloudformation-guard#14]
I'd like to test "less than or equals to" for numeric values. This allows us to test that an ECS task is compliant to resource budgets.

e.g.
```
let allowed_max_memory = 512

AWS::ECS::TaskDefinition Memory <= %allowed_max_memory
```

**Comment by nathanataws** [comment]
This is a very reasonable ask.  I'll pull this to Roadmap.

**Comment by toricls** [comment]
🚀🚀🚀

Hooray!
