### ISSUE TITLE
[BUG] Basic rule generated with rulegen failing

### ISSUE THREAD

**Issue by NickTheSecurityDude** [aws-cloudformation/cloudformation-guard#142]
Not sure if this is a bug and its probably a simple fix.

**Describe the bug**
I used rulegen on the simplest template I could make, reduced it to a single rule, and it still fails.

**To Reproduce**
`cfn-guard validate -vp  --rules secgroup-test.rules --data sg-test.yaml >secgroup-test-results.json`

**Template/Rules File/Result**
[https://github.com/NickTheSecurityDude/cfguard-testing/blob/main/sg-test.yaml](https://github.com/NickTheSecurityDude/cfguard-testing/blob/main/sg-test.yaml)
[https://github.com/NickTheSecurityDude/cfguard-testing/blob/main/secgroup-test.rules](https://github.com/NickTheSecurityDude/cfguard-testing/blob/main/secgroup-test.rules)
[https://github.com/NickTheSecurityDude/cfguard-testing/blob/main/secgroup-test-results.json](https://github.com/NickTheSecurityDude/cfguard-testing/blob/main/secgroup-test-results.json)

**Comment by dchakrav-github** [comment]
Thanks for the report. The generated rule must have been 
```
  %aws_ec2_securitygroup_resources.Properties.SecurityGroupEgress IN [{"CidrIp":"0.0.0.0/0","IpProtocol":-1},{"CidrIpv6":"::/0","IpProtocol":-1}]
```
not 

```
  %aws_ec2_securitygroup_resources.Properties.SecurityGroupEgress == [{"CidrIp":"0.0.0.0/0","IpProtocol":-1},{"CidrIpv6":"::/0","IpProtocol":-1}]
```

Sample rule with the change rule 

```bash
$ cfn-guard-2 validate -r rulegen-sg-gen.guard -d rulegen-sg.yaml 
Summary Report Overall File Status = PASS
PASS/SKIP rules
aws_ec2_securitygroup    PASS
```

**Comment by NickTheSecurityDude** [comment]
> The generated rule must have been IN not ==

I actually didn't change the generated rule :)  So its indeed putting ==

You solution kinda works, but its checking if the rules individually.

It looks like the auto-generated rule was trying to make sure Properties.SecurityGroupEgress matched both those rules, rather than checking each rule individually to see if it was in that list.  For example if I add another value to the list it still matches.

**Comment by dchakrav-github** [comment]
@NickTheSecurityDude found the bug that was introduced for backwards compatibility for 1.0. It is fixed and being tested with all examples. Direct equality does work as rulegen generated

**Comment by NickTheSecurityDude** [comment]
> @NickTheSecurityDude found the bug that was introduced for backwards compatibility for 1.0. It is fixed and being tested with all examples. Direct equality does work as rulegen generated

Cool, thanks for the quick response!

**Comment by dchakrav-github** [comment]
@NickTheSecurityDude please update the binary or use the installation via `curl` command given in [README.md](../blob/main/README.md) for MacOS/Ubuntu and verify, The fix included the example provided by you in the tests. Please re-open if you still observe the issue

**Comment by dchakrav-github** [comment]
Closing issue
