### ISSUE TITLE
[Enhancement] Print scanned template when running against a directory

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-guard#146]
When running Guard against mulitple files (`cfn-guard validate --rules file --data direcory/`), It's impossible to see which files failed (for multiple rules you could make sure that names are unique, but there is a chance of a similar problem)

Eg.
```
~$ cfn-guard validate --rules file --data direcory/
Summary Report Overall File Status = PASS
PASS/SKIP rules
optional_names    PASS
Summary Report Overall File Status = FAIL
PASS/SKIP rules
FAILED rules
optional_names    FAIL
```

You can't see from the output which file had a problem.

**Describe the solution you'd like**
When using a directory, it would be nice if the (relative) filename was also displayed

E.g.
```
~$ cfn-guard validate --rules file --data direcory/
file01.json: Summary Report Overall File Status = PASS
PASS/SKIP rules
optional_names    PASS
file02.json: Summary Report Overall File Status = FAIL
PASS/SKIP rules
FAILED rules
optional_names    FAIL
```

Rules from a directory could optionally take a similar approach (assuming file called `rules.guard` in the rules directory):

```
~$ cfn-guard validate --rules rule-directory/ --data data-direcory/
file01.json: Summary Report Overall File Status = PASS
PASS/SKIP rules
rules.guard/optional_names    PASS
file02.json: Summary Report Overall File Status = FAIL
PASS/SKIP rules
FAILED rules
rules.guard/optional_names    FAIL
```

**Comment by dchakrav-github** [comment]
Hmm. this got reverted during our push to GA. Will send a PR soon.

**Comment by dchakrav-github** [comment]
Closing this as the fix is now merged. Please re-open if you see any issues
