### ISSUE TITLE
Pre-built binaries

### ISSUE THREAD

**Issue by toricls** [aws-cloudformation/cloudformation-guard#15]
It would be great if the project host pre-built binaries for major OS platforms through the GitHub release.

(and if it provides additional support for Homebrew installation for macOS, I'm going to dance with it :heart:)

**Comment by toricls** [comment]
Here is just for someone who wants to try it out, I'm using VSCode's remote container as published in my GitHub repository here: https://github.com/toricls/cfn-guard-ecs-example

**Comment by nathanataws** [comment]
We're working out the details for this now.  What package managers would people prefer?  Our initial list is something like:

1. Homebrew,
2. Apt,
3. Yum,
4. Chocolatey

But we'd love to know what the community wants rather than make assumptions.

**Comment by nathanataws** [comment]
> Here is just for someone who wants to try it out, I'm using VSCode's remote container as published in my GitHub repository here: https://github.com/toricls/cfn-guard-ecs-example

This is _awesome_.  Nicely done!

**Comment by rahulgarg05** [comment]
Pre-built binaries for Homebrew and Chocolatey package managers released. We are keeping this GitHub issue open to track for Yum and Apt.

**Comment by gandhek** [comment]
@toricls our current Guard version 2.0 is available on homebrew and cargo. If you need support for any other package managers, please feel free to open another issue. Thank you!
