### ISSUE TITLE
cfn-guard-lambda Expected Results?

### ISSUE THREAD

**Issue by Relativity11** [aws-cloudformation/cloudformation-guard#153]
Having issues with cfn-guard-lambda results
- It's unclear to me what proper result is expected in Lambda. As of now, I can only produce a bootstrap file from the lambda.zip that I cannot view (Appears to be over the 3mb limit for view).
- https://github.com/aws-cloudformation/cloudformation-guard/tree/main/guard-lambda : Step 3) Ensure you're in the cfn-guard-lambda directory. Is this directory created or included during a git clone? I have not had a cfn-guard-lambda directory locally.
- Are there any other examples of what a adjusted run-post install would look like?

Attached I have the rules I would like AWS Lambda to ingest and check during a stack creation.

[CFNTest3.1_rules.txt](https://github.com/aws-cloudformation/cloudformation-guard/files/6576605/CFNTest3.1_rules.txt)
[Results_2.txt](https://github.com/aws-cloudformation/cloudformation-guard/files/6577361/Results_2.txt)

**Comment by Relativity11** [comment]
My current issue appears to be a base64 issue:
Tried with and without file://

[jakuna@fedora guard-lambda]$ aws lambda invoke --function-name cfnGuard  --payload '{"data": "file://CFNTest3.1.json", "rules" : "file://CFNTest-rules.txt"}'   output.json

Invalid base64: "{"data": "file://CFNTest3.1.json", "rules" : "file://CFNTest-rules.txt"}"
[jakuna@fedora guard-lambda]$ aws lambda invoke --function-name cfnGuard  --payload '{"data": "CFNTest3.1.json", "rules" : "CFNTest-rules.txt"}'   output.json

Invalid base64: "{"data": "CFNTest3.1.json", "rules" : "CFNTest-rules.txt"}"
[jakuna@fedora guard-lambda]$

**Comment by dchakrav-github** [comment]
@Relativity11 thanks for the issue report. 
1. cfn-guard is the binary that is used for local validation and testing
2. cfn-guard-lambda is a wrapper used inside AWS Lambda for validation.

The output from cfn-guard-lambda is the same as cfn-guard run with `-p -v` flags. Please run with these flags for the rules you need to test and update the issue? 

Are you running into issues running `cfn-guard-lambda` invocation locally or only on AWS Lambda?

**Comment by Relativity11** [comment]
@dchakrav-github Thank you for the response.

I have included my compiling results that I am getting both on fresh VM's of Fedora and Ubuntu.
My step methods are:

1.) cd and navigate to proper directory
2.) git clone git clone https://github.com/aws-cloudformation/cloudformation-guard
3.) cd cloudformation-guard/guard-lambda

It is here that I follow instructions of https://github.com/aws-cloudformation/cloudformation-guard/tree/main/guard-lambda

4.) Verify dependencies are satisifed.
5.) On Ubuntu - create file "config" ~/.cargo/config:
[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
6.) run cargo build --release --target x86_64-unknown-linux-musl
Results in compiling failure on both Ubuntu and Fedora "= note: the `x86_64-unknown-linux-musl` target may not be installed". 

I have also tried to use the following command:
rustup target add x86_64-unknown-linux-musl
Which installs necessary requirements on Fedora while just notifying me that 'info: component 'rust-std' for target 'x86_64-unknown-linux-musl' is up to date'

It is still very unclear to me what step 3. refers to.
_3. Ensure you're in the cfn-guard-lambda directory_
A clone of cloudformation-guard includes a subdirectory of "guard-lambda" not "cfn-guard-lambda".

I have included my new results on a fresh installation run that continues to fail.
Any help is appreciated!
[Fedora-FailedtoCompile.txt](https://github.com/aws-cloudformation/cloudformation-guard/files/6599567/Fedora-FailedtoCompile.txt)
[FedoraContinued-FailedtoCompile.txt](https://github.com/aws-cloudformation/cloudformation-guard/files/6599568/FedoraContinued-FailedtoCompile.txt)
[Ubuntu-FailedtoCompile.txt](https://github.com/aws-cloudformation/cloudformation-guard/files/6599571/Ubuntu-FailedtoCompile.txt)

**Comment by Relativity11** [comment]
[Update] 
I think I managed to get cfn-guard-lambda to successfully compile on Fedora Linux -- Though still unsuccessful on Ubuntu/Mac following this x86_64-unknown-linux-musl requirement.

[jakuna@fedora CFNGuard 2.0]$ aws lambda invoke --function-name cfn-guard-lambda  --payload '{"data": "fileb://CFNTest3.1.json", "rules" : "fileb://CFNTest3.1.rules"}' output.json --cli-binary-format raw-in-base64-out
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}

It looks like on Fedora I am able to invoke the lambda function that gets created but it doesn't seem to do anything outside of the success status code. Unfortunately, I don't really know what I should be seeing to say the compile and invoke successfully completed. Currently on 2.0.1
![Screen Shot 2021-06-07 at 10 44 42 AM](https://user-images.githubusercontent.com/11866698/121037615-96d03900-c77d-11eb-8a48-bb2630a12ff4.png)
