### ISSUE TITLE
Support existence check for resource properties

### ISSUE THREAD

**Issue by toricls** [aws-cloudformation/cloudformation-guard#16]
like "AWS::ECS::TaskDefinition TaskRoleArn is not empty" :)

**Comment by toricls** [comment]
I guess this could be related to #3

**Comment by nathanataws** [comment]
There's a flag on the `cfn-guard` tool that sounds like a match for what you're trying to do:

```
-s, --strict-checks    Fail resources if they're missing the property that a rule checks
```
Essentially, if you define a rule for a resource type around a property and the resource doesn't have that property (even if it would normally be optional), the template will fail the check.

Looking at the README, this feature is a bit hard to discover from reading.  We'll update the docs to make it more prevalent.

Let us know if that addresses your use-case.

**Comment by toricls** [comment]
@nathanataws Good to know!!

Yeah I found the option here :) https://github.com/aws-cloudformation/cloudformation-guard/tree/master/cfn-guard#runtime-arguments

So should I close this issue or change the title & description to suggest explicit/clear documentation around that option?

**Comment by nathanataws** [comment]
Don't worry about it. I'll update the doc and use this issue for the commit, then resolve it. 

I apologize for it getting so buried. I didn't realize how far down the README it was till I saw this issue.
