### ISSUE TITLE
cfn-guard test should fail when test file isn't found

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cloudformation-guard#160]
Pretty simple `cfn-guard test -r rules.txt -t test.yaml` will pass and exit with `0` if `test.yaml` doesn't exist.

**Comment by joshfried-aws** [comment]
hi @kddejong we have merged a fix for this issue https://github.com/aws-cloudformation/cloudformation-guard/pull/275. Feel free to test it out again, and re-open if you find anything more.

Thanks,
