### ISSUE TITLE
have dashes in the key names when writing rules

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cloudformation-guard#161]
Worth noting, or having a documentation improvement.  It seems like a dash is a special character and needs to be quoted when writing rules.  I'm not sure if there are other special characters I just ran into this one.  I tried to find something on the documentation for this but wasn't able to track it down.

If i have template
```yaml
--- 
key-with-dash: true
```

I cannot have a rule
```
key-with-dash == true
```
results in 
```
Parsing error handling rule file = rules.guard, Error = Parser Error when parsing rules file Parsing Error Error parsing file rules.guard at line 1 at column 1, when handling , fragment key-with-dash == true
```

The valid rule syntax is 
```
"key-with-dash" == true
```

**Comment by joshfried-aws** [comment]
Hi @kddejong, we have addressed this as part of #397. I am going to go ahead and close out this issue now. Feel free to reopen if need be. 

Thanks
