### ISSUE TITLE
[Enhancement] Add overall summary in verbose JSON output

### ISSUE THREAD

**Issue by sfarazkazmi** [aws-cloudformation/cloudformation-guard#163]
**Is your feature request related to a problem? Please describe.**

When using verbose output, customers have to calculate the overall status themselves. I want to see the verbose output for debugging purpose but in general I want the overall status only. I don't want to run the tool twice to get both form of outputs. 

**Describe the solution you'd like**

In the verbose output, add a section on top for overall summary (Pass/Fail/Skip). Also add documentation on how this is calculated (truth table) so customers can understand it better.

**Describe alternatives you've considered**

1) Run tool twice. Once with verbose and once without it.
2) Compute overall by processing verbose output. 

Both of these are extra overhead for customer.

**Additional context**

None

**Comment by priyap286** [comment]
This request of yours should be addressed by #154 where we made improvements to the output format of the `validate` command. Please refer to that for more information. I am closing this issue as I do not see any open issues. Please feel free to provide more context regarding your request and reopen the issue if you feel your issue has not been addressed.
