### ISSUE TITLE
[BUG] ParseTree returns error information twice

### ISSUE THREAD

**Issue by sfarazkazmi** [aws-cloudformation/cloudformation-guard#168]
**Describe the bug**
When using parse-tree command, error information in printed twice with slightly different text.

**To Reproduce**
Please supply:

`var status = ['ACTIVE'] `

**NOTE: Please be sure that the templates, rules and logs you provide as part of your bug report do not contain any sensitive information.**

**Expected behavior**
There should be one error log instead of duplication. Ideally should be Json format
[
{ "errorType": "ParsingError", "ErrorMessage": "Error parsing file  at line 1 at column 1, when handling , fragment var status = ['ACTIVE']"},
{other line errors},
{other line errors},
]

**Screenshots**
Output from Guard is 
`Parsing error handling rule, Error = Parser Error when parsing rules file Parsing Error Error parsing file  at line 1 at column 1, when handling , fragment var status = ['ACTIVE']

Error occurred Parser Error when parsing rules file Parsing Error Error parsing file  at line 1 at column 1, when handling , fragment var status = ['ACTIVE']
`

**Operating System:**
[eg, MacOS, Windows, Ubuntu, etc]
Linux
**OS Version**
[eg Catalina, 10, 18.04, etc]

**Additional context**

**Comment by joshfried-aws** [comment]
Hi @sfarazkazmi this has been fixed as part of #368. I am going to go ahead and close this issue.

Feel free to reopen if you feel the need. 

Thanks
