### ISSUE TITLE
[Enhancement] CloudFormation template for cfn-guard-lambda

### ISSUE THREAD

**Issue by gandhek** [aws-cloudformation/cloudformation-guard#172]
**Is your feature request related to a problem? Please describe.**
Related to manual provisioning of lambda

**Describe the solution you'd like**
An easy to deploy cloud formation template/CDK code snippet that will provision the cfn-guard-lambda in my account

**Describe alternatives you've considered**

Currently set up manually

**Additional context**

Related to: https://github.com/aws-cloudformation/cloudformation-guard/pull/57
https://github.com/aws-cloudformation/cloudformation-guard/pull/60

**Comment by PatMyron** [comment]
tracking in https://github.com/aws-cloudformation/cloudformation-guard/issues/10
