### ISSUE TITLE
[Enhancement]  Exclude unit test files when recursive scanning directory's for rule files.

### ISSUE THREAD

**Issue by TheFlexican** [aws-cloudformation/cloudformation-guard#175]
**Is your feature request related to a problem? Please describe.**

Exclude unit test files when recursive scanning directory's for rule files.

**Describe the solution you'd like**

When using cfn-guard validate -d ../path/cloudformation.yaml -r ../path/to/rules it scans _tests.yaml files. These files of course fail to parse.

**Describe alternatives you've considered**

Moving unit test files out of the directory structure, but that can become a mess real quick with multi rule files per resource.
I like a structure like this:
   rules/s3/encryption/s3-sse.guard
   rules/s3/encryption/s3-sse_tests.yaml

**Additional context**

If this is not the intended way of working with the unit tests files, please advice on how to proper do it.

Thank you.

**Comment by dchakrav-github** [comment]
```bash
$ cfn-guard validate --help
cfn-guard-validate 
... (removed for crevity)
Note - When pointing the command to a directory, the directory may not contain a mix of 
rules and data files. The directory being pointed to must contain only data files,
or rules files.
```

As the note indicates, rules and test files are maintained in separate directories. Currently, test works specifically on running a single test file against rule. We will update it to do file name convention based matching up for testing. 

Is there an alternative you would prefer?

Current workaround that you can employ until this enhancement is completed (assuming convention of `_tests.yaml` suffixes)
```
$ find rules -type f | sort | while read -r guard; read -r test; do cfn-guard test -r $guard -t $test; done
```

**Comment by TheFlexican** [comment]
Wow, my bad, i totally missed that one from the help. Thank you for clarifying.

And thank you for the example, really helpful.
