### ISSUE TITLE
[Enhancement] Add file name convention based test file selection for the `test` command

### ISSUE THREAD

**Issue by priyap286** [aws-cloudformation/cloudformation-guard#178]
**Is your feature request related to a problem? Please describe.**

As of now the `test` command requires you to explicitly specify a test data file or a directory with test data files [link](https://github.com/aws-cloudformation/cloudformation-guard/tree/main/guard#test). Most times Guard users name their test data files with the same prefix as their rules file. This kind of convention currently exists in many programming languages. It would be convenient to a lot of users to automatically pick a test data file based on the rules filepath.

**Describe the solution you'd like**
Current command example:
```shell
cfn-guard test -r path/to/ecs_checks.guard -t path/to/ecs_checks_tests.yaml
```
It would be great to not have to specify the test data file and have the tool automatically pick a test data file based on a predefined naming convention.

Proposed command:
```shell
cfn-guard test -r path/to/ecs_checks.guard
```
The expectation from the above command is that the test is run against a test data file with filepath, "path/to/ecs_checks_tests.yaml".

**Describe alternatives you've considered**

An alternative is mentioned [here](https://github.com/aws-cloudformation/cloudformation-guard/issues/175).

**Comment by razcloud** [comment]
Please check out the Guard 2.1.0 Release that should resolve this issue.
