### ISSUE TITLE
[Enhancement] Amazon linux 2 support

### ISSUE THREAD

**Issue by 0xjjoyy** [aws-cloudformation/cloudformation-guard#190]
**Is your feature request related to a problem? Please describe.**

Pre-built binaries for amazon linux 2. Currently binaries are available for mac and ubntu.

**Describe the solution you'd like**

Ability to pull down cfn-guard binary for amazon linux 2.

**Describe alternatives you've considered**

Build from source make or cargo.

**Additional context**

**Comment by priyap286** [comment]
We would need to host AL2 as a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).

**Comment by scrthq** [comment]
Although not as ideal as having available as a pre-built binary, here's how we're currently installing on Amazon Linux 2 in Userdata as a workaround for now:

```sh
curl https://sh.rustup.rs -sSf | sh -s -- -y
export PATH="~/.guard/bin:$PATH"
cargo install cfn-guard
```

**Comment by rosskarchner** [comment]
I was looking for a good way to run cfn-guard in CloudShell, since the rustup route seems to require to much disk space. Should that be part of this discussion, or does it deserve it's own issue?

**Comment by razcloud** [comment]
Hi @0xjjoyy, the latest install scripts are compatible with AL2.  Closing this issue but please let us know if you continue to have issues.
