### ISSUE TITLE
cfn-guard support for ansible yaml files?[GENERAL ISSUE]

### ISSUE THREAD

**Issue by manepals** [aws-cloudformation/cloudformation-guard#197]
Does cfn-guard supports validation of ansible yaml files? Thanks

**Comment by priyap286** [comment]
AWS CloudFormation Guard supports any structured data in JSON and YAML format. If you run into any specific issues while running AWS CloudFormation Guard with ansible YAMl files please create a new issue describing your problem and also provide appropriate examples illustrating the problem.
