### ISSUE TITLE
[BUG] show minor /patch version with -V flag

### ISSUE THREAD

**Issue by ap00rv** [aws-cloudformation/cloudformation-guard#198]
**Describe the bug**
The `-V` flag currently only shows major version. This prevents users from knowing which minor / patch version is being used. If a user wants to know whether a bug fix /feature is present in the current binary (based on release notes), knowing installed minor / patch version is helpful. 

**To Reproduce**
Please supply:

1. Using version 2.0.3 binary, run`cfn-guard -V`
1. Observe that output is `cfn-guard 2.0` instead of something like `cfn-guard 2.x.x`

**NOTE: Please be sure that the templates, rules and logs you provide as part of your bug report do not contain any sensitive information.**

**Expected behavior**
Passing the --version or -V flag should show minor and patch version as well.

**Operating System:**
Amazon Linux 2 

**OS Version**
5.4.129-72.229.amzn2int.x86_64

**Additional context**

**Comment by priyap286** [comment]
This has been addressed in https://github.com/aws-cloudformation/cloudformation-guard/pull/179. It is not available in the latest release but you can get this change by building the package locally.
