### ISSUE TITLE
Mapping of logical-ids

### ISSUE THREAD

**Issue by shaipai2** [aws-cloudformation/cloudformation-guard#200]
Hi,
Would like to know if there is a way to check if a logical-id of a resource is used in another resource. For Ex - in this CFN snippet. I would like to check if the Secret - MySecret has a corresponding RotationSchedule. For this I want to check if the logical-id **MySecret** is referred in **MySecretRotationSchedule/Properties/SecretId**.

  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This is a secret that I want to attach a resource-based policy to
      SecretString: '{"username":"MasterUsername","password":"secret-password"}'
      KmsKeyId: abcd
  MySecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: SecretDocDBClusterAttachment
    Properties:
      SecretId:
        Ref: MySecret
      RotationLambdaARN: arn:aws:lambda:us-east-1:913094140084:function:abcd
      RotationRules:
        AutomaticallyAfterDays: 30

**Comment by gauravmittal1981** [comment]
+1

**Comment by priyap286** [comment]
Please look at the example provided by @dchakrav-github on [here](https://github.com/aws-cloudformation/cloudformation-guard/issues/184#issuecomment-878729466). That should help you with your question.

Closing the request as there are no more open question. Please reopen this issue if you think the question was not addressed.
