### ISSUE TITLE
cfn-guard validate --print-json does not work

### ISSUE THREAD

**Issue by alexpulver** [aws-cloudformation/cloudformation-guard#203]
**Describe the issue**

The `validate` command includes a `-p, --print-json` flag:
```bash
$ cfn-guard validate -h
<snip>
USAGE:
    cfn-guard validate [FLAGS] [OPTIONS] --rules <rules>

FLAGS:
<snip>
    -p, --print-json              Print output in json format
<snip>
```

But it doesn't seem to have any effect:
```
$ cfn-guard validate -d template.json -r rules.guard
template.json Status = FAIL
FAILED rules
rules.guard/aws_s3_bucket_versioning_defined    FAIL
---
Evaluation of rules rules.guard against data template.json
--
Property [/Resources/WebsiteBucket4326D7C2/Properties] in data [template.json] is not compliant with [rules.guard/aws_s3_bucket_versioning_defined] because needed value at [{"AccessControl":"PublicRead"}] did not exist. Error Message [VersioningConfiguration is not defined]
--

$ cfn-guard validate -p -d template.json -r rules.guard
template.json Status = FAIL
FAILED rules
rules.guard/aws_s3_bucket_versioning_defined    FAIL
---
Evaluation of rules rules.guard against data template.json
--
Property [/Resources/WebsiteBucket4326D7C2/Properties] in data [template.json] is not compliant with [rules.guard/aws_s3_bucket_versioning_defined] because needed value at [{"AccessControl":"PublicRead"}] did not exist. Error Message [VersioningConfiguration is not defined]
--
```

Using `-o json` works. Should `-p` be a working implementation?

**Any examples**
Please supply:

1. Example rules and template that you have tried
1. The commands you used to invoke the tool
1. The output of a `-v` log level if it's not related to cfn-guard-lambda, or the relevant CloudWatch log messages if it is related to the cfn-guard-lambda

**NOTE: Please be sure that the templates, rules and logs you provide as part of your issue do not contain any sensitive information.**

**Operating System:**
[eg, MacOS, Windows, Ubuntu, etc]

macOS

**OS Version**
[eg Catalina, 10, 18.04, etc]

Catalina 10.15.7

**Additional context**

**Comment by dchakrav-github** [comment]
Current `--print-json` is coupled with `-v` verbose. We have fixed this in the upcoming release.

**Comment by razcloud** [comment]
Please check out the Guard 2.1.0 Release that should resolve this issue.

**Comment by alexpulver** [comment]
@razcloud thanks for looking into this! I don't think it should be closed yet. Running the 2.1.0 version on the below example produces both non-JSON and JSON outputs. The lower JSON output doesn't contain the CDK-Path element (in case of CDK-generated templates).

Command
```
cfn-guard validate -d template.json -r rules.guard -p > output.json
```

template.json
```
{
  "Resources": {
    "WebsiteBucket4326D7C2": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "AccessControl": "PublicRead"
      },
      "Metadata": {
        "aws:cdk:path": "LandingPageFrontend/Website/Bucket/Resource"
      }
    }
  }
}
```

rules.guard 
```
let aws_s3_bucket_resources = Resources.*[ Type == 'AWS::S3::Bucket' ]

rule aws_s3_bucket_versioning_defined {
  when %aws_s3_bucket_resources not empty {
    %aws_s3_bucket_resources {
      Properties {
        VersioningConfiguration exists <<VersioningConfiguration is not defined>>
      }
    }
  }
}
```
