### ISSUE TITLE
Error with test command when using JSON file

### ISSUE THREAD

**Issue by Yawnek** [aws-cloudformation/cloudformation-guard#206]
Hi,
We have a problem with AWS Guard. There are two main commands to run, one is validate and the other one is test. The validate one works with both JSON and YAML files as you can see :
<img width="454" alt="Capture" src="https://user-images.githubusercontent.com/46638562/135773417-1c1bd3af-c3e4-4967-8b88-1eb4adbb9ae5.PNG">
<img width="456" alt="Capture" src="https://user-images.githubusercontent.com/46638562/135773434-4ae4f640-80e8-400a-b068-527e078f9c63.PNG">

But for the test option it works only with YAML files but not JSON files, whenever I run the tool with a JSON file I get this error :

<img width="461" alt="Capture" src="https://user-images.githubusercontent.com/46638562/135773456-b2e35414-8da0-40ab-8f67-98fdd883c61e.PNG">
 

“Error processing Parser Error when parsing rules file Unable to process data in file deploy.cf.json, Error invalid type: map, expected a sequence at line 1 column 0,“

	

I tried a lot of JSON files and every time I got the same error. It seems that the system can not test JSON files, but can only run YAML files.

<img width="461" alt="Capture" src="https://user-images.githubusercontent.com/46638562/135773466-45b3f28e-cb05-4852-b930-131e79e87427.PNG">

[api_gate_private - Copy.txt](https://github.com/aws-cloudformation/cloudformation-guard/files/7278772/api_gate_private.-.Copy.txt)
[example(json).txt](https://github.com/aws-cloudformation/cloudformation-guard/files/7278773/example.json.txt)
[deploy.cf(json).txt](https://github.com/aws-cloudformation/cloudformation-guard/files/7279054/deploy.cf.json.txt)

**Comment by Yawnek** [comment]
[api_gate_private - Copy.txt](https://github.com/aws-cloudformation/cloudformation-guard/files/7278767/api_gate_private.-.Copy.txt)
[example(json).txt](https://github.com/aws-cloudformation/cloudformation-guard/files/7278768/example.json.txt)

**Comment by dchakrav-github** [comment]
@Yawnek thanks for bug report. The `test` command is for unit testing Guard rules that are written. They have specific format for specifying and running unit tests. See [Unit Tests](https://github.com/aws-cloudformation/cloudformation-guard/blob/main/docs/UNIT_TESTING.md) for what is the expected structure. 

You should use `validate` command to validate a CFN template. You use `test` command to run unit tests for the rules. With the upcoming release, we have added support to run all included unit tests for a given directory of rules.

**Comment by Yawnek** [comment]
Thank you for your help.
It works.
Thank you,
