### ISSUE TITLE
[GENERAL ISSUE] Improve code quality

### ISSUE THREAD

**Issue by priyap286** [aws-cloudformation/cloudformation-guard#208]
**Describe the issue**
Improve code quality and code test coverage.
Eg. https://github.com/aws-cloudformation/cloudformation-guard/pull/201#discussion_r730546785

**Any examples**
N/A

**NOTE: Please be sure that the templates, rules and logs you provide as part of your issue do not contain any sensitive information.**

**Operating System:** N/A
[eg, MacOS, Windows, Ubuntu, etc]

**OS Version** N/A
[eg Catalina, 10, 18.04, etc]

**Comment by joshfried-aws** [comment]
While we are always going to have some cleanup to do in our code base I think after merging #371 , #325, #324, #322, and #315 we are now ready to close this issue out.
