### ISSUE TITLE
[BUG] Unknown parse error

### ISSUE THREAD

**Issue by Yawnek** [aws-cloudformation/cloudformation-guard#218]
Hi,
We have a problem with AWS Guard. There are two main commands to run, one is validate and the other one is test. The validate one works with both JSON and YAML files as you can see :

	
<img width="645" alt="Capture" src="https://user-images.githubusercontent.com/46638562/140856928-8186b44d-a896-4546-8d70-422a45da6278.PNG">

But for the test option it  doesnt seeem to work. I try different files even empty one, and I still get this error :

“Error processing Parser Error when parsing rules file Unable to process data in file deploy.cf.json, Error invalid type: map, expected a sequence at line 1 column 0,“

I can get different number lines but the message stay the same

The sample code works perfectly, with the yaml format ( only for the sample ), but not our own yaml format code ( even if we believe its correct ).

I'll provide sample code in comments.

<img width="835" alt="Capture" src="https://user-images.githubusercontent.com/46638562/140857258-176d81e7-c029-43a0-aca7-aaf460aa368f.PNG">

**Comment by shreyasdamle** [comment]
Thanks for reporting. I will check and get back to you.

**Comment by shreyasdamle** [comment]
@Yawnek I wasn't able to reproduce this issue in cfn-guard `v2.0.3`. Can you please share the sample rule and test file?

**Comment by razcloud** [comment]
@Yawnek I was able to recreate on v2.0.4

<img width="427" alt="image" src="https://user-images.githubusercontent.com/34892703/168701016-9251b93e-1361-4a0c-be4e-d0a564c8dbd7.png">
On Line 19, expect a space before FAIL

<img width="658" alt="image" src="https://user-images.githubusercontent.com/34892703/168701056-dd2bfb05-687c-4aa1-a818-3c80a53fb94d.png">

Adding the correct space and then runs as expected.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/34892703/168701106-a106fc1a-d8f1-49c1-80b2-4aae0065c7b6.png">

<img width="645" alt="image" src="https://user-images.githubusercontent.com/34892703/168701139-f1d6f0e2-6b00-4ba6-b96b-4fc5307d08b6.png">


Will bring this back to the team to discuss.
