### ISSUE TITLE
[Enhancement] Add line number of analyzed file into the json report

### ISSUE THREAD

**Issue by trickstyler** [aws-cloudformation/cloudformation-guard#219]
**Is your feature request related to a problem? Please describe.**

I'd like to use the JSON format when analyzing the files but the line number doesn't appear when i `cfn-guard validate -p --show-clause-failures  --data template.json --rules rules.guard  --output-format json`

**Describe the solution you'd like**

Have the returned JSON file include the exact position of the found rule error in the file in a format of 'line:column'
so i'll be able to use it to locate the problem in the analyzed file

**Describe alternatives you've considered**

I could deserialize the Clause Failure Summary and find the line and column manually but that's not really a standard way
because it's subject to changes and does not guarantee the format

**Additional context**

Any speedy response would be highly appreciated

**Comment by shreyasdamle** [comment]
@trickstyler Thanks! We are going to add support for this feature in next release.

**Comment by razcloud** [comment]
Please check out the Guard 2.1.0 Release that should resolve this issue.
