### ISSUE TITLE
Feature Request: Add support for the pre-commit framework

### ISSUE THREAD

**Issue by dontirun** [aws-cloudformation/cloudformation-guard#22]
The [pre-commit framework](https://pre-commit.com/) is a commonly used tool to create git hooks for code validation. Other AWS tools such as [cfn-python-lint](https://github.com/aws-cloudformation/cfn-python-lint) provide support for the framework

**Comment by nathanataws** [comment]
This is very reasonable ask.  We're looking at integrations right now.  We'll pull this into that discussion.

**Comment by jotompki** [comment]
Looks like pre-commit natively supports rust as a [buildable language plugin](https://pre-commit.com/#rust). If this is the case, this should be straightforward to offer.

**Comment by benbridts** [comment]
There are still some hurdles (at least  the last time I tried):
- You need to have rust installed (not much to do about that, and you can install cfn-guard yourself and use the system "language")
- pre-commit passes all matching files on one invocation (or at least does so by default). I couldn't get it to invoke cfn-guard multiple times (that's why I created #62 )

**Comment by barnesrobert** [comment]
+1 to this issue. Pre-commits are a vital way of remediating latent vulnerabilities before they're committed.

**Comment by kgrvamsi** [comment]
Do we have any update on this Feature request to support pre-commit hooks?

**Comment by joshfried-aws** [comment]
Hi @kgrvamsi we do not have any updates here yet.

**Comment by dannyvassallo** [comment]
@kgrvamsi the initial implementation with documentation has been merged to the main branch of the repo. I'm going to close this issue and we can track anything that comes up in the future in a new one. Thanks to everyone for their patience on this and we hope you enjoy using the new hook!
