### ISSUE TITLE
[BUG] Error does not indicate that a file was 0 bytes. 

### ISSUE THREAD

**Issue by Yawnek** [aws-cloudformation/cloudformation-guard#225]
Hi,
When you use the command validate on a 0 bytes file. 
The error you get is : 
Error occurred I/O error when reading No such file or directory (os error 2)

Thank you.

**Comment by joshfried-aws** [comment]
Hi @Yawnek  this issue was addressed as part of #370. I will go ahead and close this issue for now feel free to reopen if need be.

Thanks
