### ISSUE TITLE
[Enhancement] Ignore(don't output errors) invalid json or yaml files when recursive scanning directories

### ISSUE THREAD

**Issue by TheFlexican** [aws-cloudformation/cloudformation-guard#227]
**Is your feature request related to a problem? Please describe.**

We use CFN-Guard in a pipeline, and are using a recursive scan on the source repository to find all json and yaml files. The CFN-Guard validate command  -data option can't take ./ as an input, so i wrote something like below.

```
for d in */ ; do
    files=`find $d* -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.json" \)`
    for f in $files; do
       cfn-guard validate -d "$f" -r ./rules --output-format json --show-summary none >> validate.json.tmp
    done
done
```
This will scan all yaml and json files in the source repository. Issue that can happen is it will find a json or yaml file that's either empty or some other issue with the file, and an error like below is generated.

`Error occurred Error parsing incoming YAML context EOF while parsing a value`
or
`Error occurred I/O error when reading No such file or directory (os error 2)`

When we pipe the output of cfn-guard to a json file, and then try to parse it with JQ we get errors, so we have to do some hack to grep only valid responses from cfn-guard like below.
`egrep '{"data_from":' validate.json.tmp | jq -s . > validate.json`

This is a ugly solution, and I rather not use it, but I can't think of a different way to only get the valid parsing results. We want to have a json array, so we can parse it with our Python script to find non compliant resources, and report back to user in the codebuild output and also send out email and/or ms teams notifications.

**Describe the solution you'd like**

Add a parameter to cfn-guard validate, that will let us chose whether we want to see output of failed/invalid file parses. Another idea is that we can specify were we want the valid and the error output to be logged for cfn-guard validate.

**Describe alternatives you've considered**

See above, using grep to find valid parses from cfn-guard output

**Additional context**

**Comment by razcloud** [comment]
Thank you for closing this @TheFlexican
