### ISSUE TITLE
[Enhancement] bash completions using clap-rs automatic generators.

### ISSUE THREAD

**Issue by sepehrdaddev** [aws-cloudformation/cloudformation-guard#229]
**Is your feature request related to a problem? Please describe.**
I'd like to use bash completions when I'm using `cfn-guard` since its really convenient when I forget the commands or arguments that are required by `cfn-guard`.

**Describe the solution you'd like**
Have `cfn-guard` generate bash completions using a command e.g. `cfn-guard completions bash`.

**Describe alternatives you've considered**
I use the help command mostly which slows down my workflow.

**Additional context**
`cfn-guard` uses `clap-rs` as it's argument parser and `clap-rs` provides automatic shell completion generation for major shells.

Clap shell [documentations](https://docs.rs/clap/latest/clap/struct.App.html#method.gen_completions)

**Comment by joshfried-aws** [comment]
Hi @sepehrdaddev we have added this feature in #340. 

I am going to go ahead and close this PR. Feel free to reopen if need be!
