### ISSUE TITLE
DSL - but aren't there any default CloudFormation rules (eg. Conformance Packs)

### ISSUE THREAD

**Issue by markl11** [aws-cloudformation/cloudformation-guard#230]
Hi,

I understand that cfn-guard is a DSL, but aren't there any default rules to validate compliance with? For example, example rules that check compliance with AWS Config Conformance Packs or Security Hub standards would be extremely useful as we shift-left....

If there are not default rules then I think most people will just ignore cfn-guard to be honest (the community will just continue to use Checkov, cfn-nag, etc, etc)

Thanks

**Comment by Poweranimal** [comment]
I can only agree.
Asked me the same question...

**Comment by razcloud** [comment]
Please check out the AWS Guard Rules Registry which was recently open sourced:  https://github.com/aws-cloudformation/aws-guard-rules-registry
