### ISSUE TITLE
[BUG] Wrong output with --type CFNTemplate when Properties Key not used

### ISSUE THREAD

**Issue by akumar-99** [aws-cloudformation/cloudformation-guard#235]
**Describe the bug**
The output should have resource names in non_compliant list instead shows `Rule s3_access_logging Resource 0 1`. This is a case specific when Cloudformation resources are without `Properties` keyword.
Command: 
`cfn-guard validate --data templates/s3.yaml --rules rules/s3   --type CFNTemplate`

**To Reproduce**

**S3.yaml**
```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  LogicalID1:
    Type: AWS::S3::Bucket
```
**Rule Definition**
```
let s3_buckets = Resources.*[
   Type == "AWS::S3::Bucket"
]

rule s3_access_logging when %s3_buckets !empty {
   %s3_buckets {
      Properties exists
   }
}
```

**Output: cfn-guard validate --data templates/s3.yaml --rules rules/s3  -o json --type CFNTemplate -v**
```
{
   "data_from":"s3.yaml",
   "rules_from":"s3",
   "not_compliant":{
      "Rule s3_access_logging Resource 0 1":[
         {
            "rule":"s3_access_logging",
            "path":"",
            "provided":{
               "Type":"AWS::S3::Bucket"
            },
            "expected":null,
            "comparison":{
               "operator":"Exists",
               "not_operator_exists":false
            },
            "message":""
         }
      ]
   },
   "not_applicable":[
      
   ],
   "compliant":[
      
   ]
}

Evaluation Tree
Rule(s3_access_logging, FAIL)
    |  Message: DEFAULT MESSAGE(FAIL)
    Condition(s3_access_logging, PASS)
        |  Message: DEFAULT MESSAGE(PASS)
        Clause(Clause(Location[file:s3, line:5, column:29], Check: %s3_buckets NOT EMPTY ), PASS)
            |  From: Map((Path("/Resources/LogicalID1"), MapValue { keys: [String((Path("/Resources/LogicalID1/Type"), "Type"))], values: {"Type": String((Path("/Resources/LogicalID1/Type"), "AWS::S3::Bucket"))} }))
            |  Message: DEFAULT MESSAGE(PASS)
    BlockClause(Block[Location[file:s3, line:6, column:2]], FAIL)
        |  Message: DEFAULT MESSAGE(FAIL)
        Conjunction(cfn_guard::rules::exprs::GuardClause, FAIL)
            |  Message: DEFAULT MESSAGE(FAIL)
            Clause(Clause(Location[file:s3, line:7, column:9], Check: Properties  EXISTS ), FAIL)
                |  From: Map((Path("/Resources/LogicalID1"), MapValue { keys: [String((Path("/Resources/LogicalID1/Type"), "Type"))], values: {"Type": String((Path("/Resources/LogicalID1/Type"), "AWS::S3::Bucket"))} }))
                |  Message: (DEFAULT: NO_MESSAGE)
```

**Expected behavior**
The output should have resource name i.e. `LogicalID1` instead of `Rule s3_access_logging Resource 0 1`.

**Operating System:**
Fedora

**OS Version**
35

**Additional context**

**Comment by joshfried-aws** [comment]
Hi @akumar-99 this issue seems to be addressed with the release of guard 3.0.0 

Running the same template, and rule i got the following output 

`cfn-guard validate -r 235.guard -d 235.yaml -o json -v --type CFNTemplate
235.yaml Status = FAIL
FAILED rules
235.guard/s3_access_logging    FAIL
---
{
  "name": "235.yaml",
  "metadata": {},
  "status": "FAIL",
  "not_compliant": [
    {
      "Rule": {
        "name": "s3_access_logging",
        "metadata": {},
        "messages": {
          "custom_message": null,
          "error_message": null
        },
        "checks": [
          {
            "Clause": {
              "Unary": {
                "context": " Properties EXISTS  ",
                "messages": {
                  "custom_message": "",
                  "error_message": "Check was not compliant as property [Properties] is missing. Value traversed to [Path=/Resources/LogicalID1[L:3,C:4] Value={\"Type\":\"AWS::S3::Bucket\"}]."
                },
                "check": {
                  "UnResolved": {
                    "value": {
                      "traversed_to": {
                        "path": "/Resources/LogicalID1",
                        "value": {
                          "Type": "AWS::S3::Bucket"
                        }
                      },
                      "remaining_query": "Properties",
                      "reason": "Could not find key Properties inside struct at path /Resources/LogicalID1[L:3,C:4]"
                    },
                    "comparison": [
                      "Exists",
                      false
                    ]
                  }
                }
              }
            }
          }
        ]
      }
    }
  ],
  "not_applicable": [],
  "compliant": []
}`- File(235.yaml, Status=FAIL)[Context=File(rules=1)]
   `- Rule(s3_access_logging, Status=FAIL)[Context=s3_access_logging]
      |- Rule/When(Status=PASS)[Context=Rule#s3_access_logging/When]
      |  `- GuardClauseBlock(Status = PASS)[Context=GuardAccessClause#block %s3_buckets not EMPTY  ]
      |     |- Filter/ConjunctionsBlock(Status=PASS)[Context=Filter/Map#1]
      |     |  `- GuardClauseBlock(Status = PASS)[Context=GuardAccessClause#block Type EQUALS  "AWS::S3::Bucket"]
      |     |     `- GuardClauseValueCheck(Status=PASS)[Context= Type EQUALS  "AWS::S3::Bucket"]
      |     `- GuardClauseValueCheck(Status=PASS)[Context= %s3_buckets not EMPTY  ]
      `- GuardValueBlockCheck(Status = FAIL)[Context=BlockGuardClause#Location[file:235.guard, line:7, column:4]]
         `- GuardClauseBlock(Status = FAIL)[Context=GuardAccessClause#block Properties EXISTS  ]
            `- GuardClauseUnaryCheck(Status=FAIL, Comparison= EXISTS, Value-At=(unresolved, Path=/Resources/LogicalID1[L:3,C:4] Value={"Type":"AWS::S3::Bucket"}))[Context= Properties EXISTS  ]`
            
 I am going to go ahead and close out this issue. Feel free to reopen if need be.
