### ISSUE TITLE
[GENERAL ISSUE] CFN Guard Lambda output exceeds limit

### ISSUE THREAD

**Issue by zlberto** [aws-cloudformation/cloudformation-guard#236]
The CFN Guard Lambda output exceeds the size limit, so it would be necessary to reduce the output or set a flag to send the output to S3

**Comment by akshayrane** [comment]
@zlberto We have merged a fix allowing the option (using a `verbose` flag set to `false`) to get a shorter version of output from Lambda. 

You may try it out at your end and verify if the size issue is resolved.

**Comment by razcloud** [comment]
Merged into the following branch: https://github.com/aws-cloudformation/cloudformation-guard/tree/feat-guard-lambda-s3-output

**Comment by joshfried-aws** [comment]
Hi @zlberto I am going to go ahead and close this issue since it seems like #240 addressed this issue
