### ISSUE TITLE
Question - how does it connect with open policy agent / rego based rules

### ISSUE THREAD

**Issue by amit10may** [aws-cloudformation/cloudformation-guard#258]
I see similar efforts with OPA (open policy agent) wherein we can write rules in a common language based on REGO and open policy agent can be used to evaluate it. The current project seems to also achieve similar goals. Am I missing the difference between the two projects?

**Comment by razcloud** [comment]
Hi @amit10may,

You are correct in that there are similar goals between cfn-guard and OPA, both being tools to enable policy-as-code.

One call out is that Guard is a purpose built domain-specific language (DSL) specifically for policy-as-code.  OPA is a general purpose policy engine; therefore, you can express policies against arbitrary structured data.  

Depending on your use case, one may be a better choice than the other.
