### ISSUE TITLE
JSON/YAML discrepancy when parsing functions

### ISSUE THREAD

**Issue by f0o** [aws-cloudformation/cloudformation-guard#27]
Hi,

I have a policy to check for specific tags like:
```
AWS::ElasticLoadBalancingV2::LoadBalancer Tags.0 == {"Key":"EnvironmentType","Value":"EnvironmentType"}
AWS::ElasticLoadBalancingV2::LoadBalancer Tags.1 == {"Key":"OwnerContact","Value":"OwnerContact"}
```

They work fine on YAMLs in format:
```yaml
        - Key: EnvironmentType
          Value: !Ref EnvironmentType
        - Key: OwnerContact
          Value: !Ref OwnerContact
```

However they fail on JSON:

```json
          { "Key" : "EnvironmentType", "Value" : { "Ref" : "EnvironmentType" } },
          { "Key" : "OwnerContact", "Value" : { "Ref" : "OwnerContact" } },
```

with the error:
```
"[Sg] failed because [Tags.0] is [{\"Key\":\"EnvironmentType\",\"Value\":{\"Ref\":\"EnvironmentType\"}}] and the permitted value is [{\"Key\":\"EnvironmentType\",\"Value\":\"EnvironmentType\"}]"
"[Sg] failed because [Tags.1] is [{\"Key\":\"OwnerContact\",\"Value\":{\"Ref\":\"OwnerContact\"}}] and the permitted value is [{\"Key\":\"OwnerContact\",\"Value\":\"OwnerContact\"}]"
```

What would be the proper way of matching both formats?

//Edit

Using `IN [{"Key":"OwnerContact","Value":"OwnerContact"},{"Key":"OwnerContact","Value":{"Ref":"OwnerContact"}}]` doesnt work either with the error:
```
"[Alb] failed because [{\"Key\":\"OwnerContact\",\"Value\":\"OwnerContact\"}] is not in [{\"Key\":\"OwnerContact\",\"Value\":\"OwnerContact\"},{\"Key\":\"OwnerContact\",\"Value\":{\"Ref\":\"OwnerContact\"}}] for [Tags.1]"
```
However I believe this should be working as the matching object is in the list. (I tried with `[[{...}],[{...}]]` same result)

//Edit2:

`== /^\{"Key":"OwnerContact","Value":"OwnerContact"\}$|^\{"Key":"OwnerContact","Value":\{"Ref":"OwnerContact"\}\}$/`
This seems to work, but I highly doubt this is how it's intended to work

**Comment by nathanataws** [comment]
You are correct.  The behaviors are different because of the different way CFn intrinsic functions are represented within the two formats.  We're working through a number of possible ways to address it.

Check out this part of the README for more info:  https://github.com/aws-cloudformation/cloudformation-guard/blob/master/cfn-guard/README.md#working-with-cloudformation-intrinsic-functions

For your second approach, try changing the `Tags` reference to a wildcard (`Tags.*`) and the "==" will match if any part of the Tags list passes.

**Comment by f0o** [comment]
The wildcard solution is sadly not applicable because it will fail on any additional tags that aren't defined in the ruleset (https://github.com/aws-cloudformation/cloudformation-guard/issues/23#issuecomment-649239774)

**Comment by nathanataws** [comment]
I added some comments to #23.  

Looking at the above, it seems like you're running into the different behaviors of the YAML vs JSON representations of the CFN intrinsic functions (like Ref).  The current guidance is if you're going to be checking YAML and JSON specifically for intrinsics, you need to cover both the representations:  https://github.com/aws-cloudformation/cloudformation-guard/tree/master/cfn-guard#working-with-cloudformation-intrinsic-functions

That said, I'm not happy about how it works right now.  We're kicking around different approaches to come up with a behavior that reconciles the different representations without being lossy or confusing.  Hopefully, we'll get an elegant, supportable solution out soon.  In the mean time, you need to use the `|OR|` with a checking for the intrinsic in JSON on one side and YAML on the other.

**Comment by nathanataws** [comment]
For example:

```
AWS::EC2::Volume AvailabilityZone == ["EC2Instance","AvailabilityZone"] |OR| AWS::EC2::Volume AvailabilityZone == {"Fn::GetAtt":["EC2Instance","AvailabilityZone"]}
```

**Comment by f0o** [comment]
Yeah I'm using regex match now instead. It's really ugly tho 😅

**Comment by nathanataws** [comment]
Check out the latest `release-0.5.2` branch.  I added JSON list literals to make the task of matching against intrinsics in both YAML and JSON templates a bit easier.

For example:

```
let tag_vals = [{"Key":"OwnerContact","Value":"OwnerContact"},{"Key":"OwnerContact","Value":{"Ref":"OwnerContact"}}]
AWS::EC2::SecurityGroup Tags.* IN %tag_vals
```
Should now work correctly for both the YAML and JSON versions you're trying to check.

**Comment by f0o** [comment]
Works and also 0.5.2 is quite a lot faster too!

Thanks :)

**Comment by nathanataws** [comment]
Awesome!  👍
