### ISSUE TITLE
[Enhancement] Check parameters

### ISSUE THREAD

**Issue by hexploder** [aws-cloudformation/cloudformation-guard#272]
**Is your feature request related to a problem? Please describe.**

Need to check parameters. As for my understanding you can only check for Resources.

**Describe the solution you'd like**

I want to be able to check for the existance of specific parameters. Then to check the properties of said parameters.
for example:
```
let parameters = Parameters.*
rule assert_parameters when %parameters !empty {
    some %parameters.ParameterName == "ProjectCode"
    some %parameters.ParameterName == "ProjectName"
    some %parameters.ParameterName == "Environment"
}
```

**Describe alternatives you've considered**

I need to check if the value of a tag is between our standard, for example:
```
Tags:
    - Key: Environment
       Value: !Ref Environment
```
I tryed to use cfn-resolver to transform the CFN and get the values instead of Ref function and then check it there but for some reasons related to the way the params.json is formed cfn-resolver doesn't work for us, so I ratter check directly the parameter.

**Additional context**

I want to check project code with a regex, for example ProjectCode should exist and it should start with either AB or AC or FAIL.
So if ProjectCode is ABHello or ACHello is going to work but if its YZHello or XZHello it will fail or to check if a specific AllowedPattern is set.
For the Environment I want to check if the AllowedValues are DEV,QA,PROD and nothing more

BTW: I'm pretty new at all this maybe there is a way to check Parameters and I haven't found the documentation.

**Comment by benbridts** [comment]
Guard can check any json or yaml document, so it does not matter if you want to check the Resources or Parameters section. 
However, there is no `ParameterName` key in CloudFormation, what you can do is write something like the following (untested) code:

```
rule required_parameters {
    Parameters.ProjectCode exists
    Parameters.ProjectName exists
    Parameters. Environment exists
}

see https://github.com/aws-cloudformation/cloudformation-guard/blob/main/docs/CLAUSES.md

**Comment by hexploder** [comment]
Oh okay I didn't saw any example or documentation about that and I thought you couldn't even use Logical IDs, that is great.

So I could also do something like

`Parameters.Environment.AllowedValues == [DEV, QA, STG, PROD]`
and
`Parameters.ProjectCode.AllowedPattern == "some_regex"`

I'll try that out thanks a lot for the help!

**Comment by razcloud** [comment]
Thank you @benbridts 

@hexploder Please let us know if you this resolves your issue.
