### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tolubewaji** [aws-cloudformation/cloudformation-guard#274]
**Describe the bug**
CloudFormation does not recognize description for IP range in SecurityGroupIngress in AWS::EC2::SecurityGroup if the description is contained within double quotes.

**To Reproduce**
Use the sample below and update from the AWS CLI using the aws cloudformation update-stack command.

  TestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Test
      GroupDescription: Test
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          Description: "SSH Port"
          CidrIp: 0.0.0.0/0    

**Expected behavior**
A security group is created. An entry with **description** *SSH Port* for port 22 is also created.

**Actual behavior**
A security group is created. Entry for port 22 has an empty description. Additionally, CloudFormation does not detect any changes if another update with the double quotes removed is attempted. 

**Operating System:**
Ubuntu

**OS Version**
20.04

**Additional context**

**Comment by razcloud** [comment]
Hi @tolubewaji This issue does not seem directly related to Guard.  Can you please clarify?

**Comment by razcloud** [comment]
Closing as this does not seem related to cfn-guard.  If assistance is needed, please provide the cfn-guard version you are using, as well as the rule and template file.  Thank you.
