### ISSUE TITLE
[BUG] cfn-guard validate --output-format doesn't produce a valid json/yaml format

### ISSUE THREAD

**Issue by omartrigui** [aws-cloudformation/cloudformation-guard#279]
**Describe the bug**

The output of `cfn-guard validate --output-format` could not be parsed without omitting the first line. A string "CFN" is always printed before the relevant data.

**To Reproduce**

```
# cfn-guard --version
cfn-guard 2.1.0

# cat template.yaml 
AWSTemplateFormatVersion: '2010-09-09'
Description: VPC function.

# cat rule.guard 
let s3_buckets = Resources.*[ Type == /S3::Bucket/ ]

# cfn-guard validate --output-format json --show-summary none -r rule.guard -d template.yaml 
CFN
{"data_from":"template.yaml","rules_from":"rule.guard","not_compliant":{},"not_applicable":[],"compliant":[]}

# cfn-guard validate --output-format yaml --show-summary none -r rule.guard -d template.yaml 
CFN
---
data_from: template.yaml
rules_from: rule.guard
not_compliant: {}
not_applicable: []
compliant: []
```

**Expected behavior**

cfn-guard validate --output-format produces a valid json/yaml format

**Operating System:**
Ubuntu

**Comment by joshfried-aws** [comment]
@omartrigui Thanks for filing this issue. We were able to reproduce the issue at our end, we will troubleshoot the issue and get back with an update soon.

**Comment by drmmarsunited** [comment]
This also seems somewhat intertwined with #180 in terms of fully valid JSON/YAML formatting on output

**Comment by joshfried-aws** [comment]
@omartrigui this issue was addressed in a previous commit. It will be included in our next release. 

Thanks
