### ISSUE TITLE
[GENERAL ISSUE] Publish 2.1.x to crates.io

### ISSUE THREAD

**Issue by seawildau** [aws-cloudformation/cloudformation-guard#288]
**Describe the issue**
There was a previous issue (#257)  raised about publishing the latest release version to crates.io so that consumers don't have to build from source or pull binaries from GitHub releases, which was blocked due to a dependency on a bugfix in yaml_rust.

As of b722c83d (#271)  this dependency on yaml_rust looks to have been removed. Are we now in a position to publish a 2.1.x latest version to crates.io?

Also, the documentation in the README still lists this dependency as an issue along with a recommendation to build from source/pull from GitHub releases. Would make sense to remove this banner at the same time.

**Comment by akshayrane** [comment]
Thanks for highlighting this, we are working on releasing the next patch version soon it might take some time while we work on some of the enhancements and bug fixes that we want to include with it.

Akshay
