### ISSUE TITLE
[Enhancement] Publish a tagged docker image on release

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-guard#293]
I'm very excited about #292 

but currently that publishes a `latest` and `${commit_hash}` image for every commit on `main`.

It would be nice if there would be one or more extra tags published when there is a release.  E.g. `2` `2.0` and `2.0.2`, that way customers can decide to only follow release (`2`, or to pin to a certain release version (`2.0.2`).

There is also an argument to be made to have `latest` be the latest released version instead of the latest commit on the main branch, but having a `2` available will solve that too

**Comment by razcloud** [comment]
Thank you for the feedback @benbridts.  Will discuss with the team.

**Comment by akshayrane** [comment]
Thank you for this recommendation @benbridts we'll do a feasibility check and post an update on this issue.

**Comment by joshfried-aws** [comment]
Hi @benbridts this has been addressed as part of #390 and we will now start releasing tagged docker images on release from now on (starting at our next release). 

I am going to go ahead and close out this issue. Feel free to reopen if need be. 

Thanks,
