### ISSUE TITLE
Disallow Certain Type/Types

### ISSUE THREAD

**Issue by nathanataws** [aws-cloudformation/cloudformation-guard#3]
Customers may need to be able to disallow entire resource types, including those types of resources that do not have any required properties.

Possible Form:
`!AWS::IAM::User`

**Comment by PatMyron** [comment]
CloudFormation actually natively supports something similar:
[`aws cloudformation create-stack --resource-types`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html#options)
[`aws cloudformation update-stack --resource-types`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/update-stack.html#options)
[`aws cloudformation create-change-set --resource-types`](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-change-set.html#options)

**Comment by shreyasdamle** [comment]
I was able to disable type using the following pattern:

`AWS::IAM::User .Type != AWS::IAM::User << IAM - User cannot be used in a secure context` 

For all use cases that I tried, it is working as expected. Please let me know if this approach is right for disallowing entire resource type.

**Comment by n1t1nv3rma** [comment]
Kind of related but at entire resource level : https://github.com/aws-cloudformation/cloudformation-guard/issues/94

**Comment by jotompki** [comment]
In #115, enhancements proposed should be able to account for this. Because one is able to select anything in the incoming template for checking/filtering, one could craft a ruleset like:
```

let disallowed_resource_types = [
    /AWS::IAM/,
    /AWS::S3/,
    /AWS::EC2::VPC/
]

rule disallowed_resource_types {
    Resources.*.Type IN %disallowed_resource_types
}
```
If any are not, the disallowed_resource_types rule will fail. Should be possible in 2.0 ruleset language.

**Comment by dchakrav-github** [comment]
Customers can easily write select in allowed list or exclude disallowed list 
```
let resources = Resource.*[ Type IN %allowed ]
```
or
```
let resources = Resource.*[ Type !IN %disallowed ]
```
