### ISSUE TITLE
Support for Terraform IAC [Enhancement]

### ISSUE THREAD

**Issue by cool-raj** [aws-cloudformation/cloudformation-guard#303]
**Is your feature request related to a problem? Please describe.**
I would like to use a CFN-guard as a single tool to validate/test my IAC ( writen in Cloudformation,CDK,teraform) against the one time defined cfn guard rules. I see so many tools in available but no one is addressing the issue apart from [Regula](https://regula.dev/about.html ) . 

**Describe the solution you'd like**
My ideal solution would be . Security team/Compliance team defines the rule in the rule format by the tool 

**Describe alternatives you've considered**

**Additional context**

**Comment by benbridts** [comment]
Would converting from HCL to JSON (like https://www.hcl2json.com/), so you can write Terraform-specific checks help?

**Comment by SWolfeCAI** [comment]
I would also see a lot of value in being able to guard against raw HCL.  Specifically I'd like to add guards to ensure best practices and our enterprise standards related to the `terraform` block.

Converting to JSON might be viable--but anecdotally I haven't had much success with 3rd party tools working as-needed and/or not breaking with terraform updates.

Our enterprise has well over 50,000 terraform modules--so one way or another I'd like to have the guard functionality to help avoid some simple pitfalls.

**Comment by razcloud** [comment]
We have no plans to address this issue or add this to the roadmap at this point in time.
