### ISSUE TITLE
arm64 support missing

### ISSUE THREAD

**Issue by aruandre** [aws-cloudformation/cloudformation-guard#314]
**Describe the bug**
Executing the install command provided on an aarch64 instance we get the following error "sh: 30: /root/.guard/bin/cfn-guard: Exec format error". It has succeeded previously. Seems like the pre-built binaries are only for x86.

`root@ip-10-172-1-229:/home/ubuntu# curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh
sh: 30: /root/.guard/bin/cfn-guard: Exec format error
cfn-guard was not installed properly`

`root@ip-10-172-1-229:/home/ubuntu# file /root/.guard/2/cfn-guard-v2-ubuntu-latest/cfn-guard
/root/.guard/2/cfn-guard-v2-ubuntu-latest/cfn-guard: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=a8df4189d762cd51d87b239ed5e9aac96ae7e040, with debug_info, not stripped`

`root@ip-10-172-1-229:/home/ubuntu# uname -a
Linux ip-10-172-1-229 5.15.0-1026-aws #30~20.04.2-Ubuntu SMP Fri Nov 25 14:54:57 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by polothy** [comment]
Also +1 for macOS ARM support too.

**Comment by polothy** [comment]
@akshayrane @joshfried-aws can this get prioritized? Would be a relatively easy fix to the GitHub workflow + install shell script.  The [cdk-validator-cfnguard](https://github.com/cdklabs/cdk-validator-cfnguard/blob/main/projenrc/bundle-guard.ts) actually bundles these binaries with the package. This means it wont work for anyone using the newer Apple computers (M1,M2,etc).  Right now, the only way I know of getting ARM support on macOS is to use [brew](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/cloudformation-guard.rb).

I'd also like to use the ARM binary for [CodeBuild ARM images](https://github.com/aws/aws-codebuild-docker-images). I think the workaround here might be to use Docker image, but haven't tested it.  It would be nice though to just have the binaries pre-built though.

**Comment by razcloud** [comment]
Hi @polothy 

Thank you for explaining your need for ARM support. Will discuss this with @joshfried-aws and @akshayrane.

**Comment by joshfried-aws** [comment]
Hi @polothy and @aruandre we have now added aarm64 support for cfn-guard as part of #387. 

I am going to go ahead and close out this issue. Feel free to reopen if need be.

Thanks,

**Comment by polothy** [comment]
Yes, awesome, thanks!
