### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by brilliantarticles** [aws-cloudformation/cloudformation-guard#32]
**Describe the bug**

**To Reproduce**
Please supply:

1. An example rule set and template that results in the error
1. The commands you used to invoke the tool
1. The output of a `-vvv` log level if it's not related to cfn-guard-lambda, or the relevant CloudWatch log messages if it is related to the lambda

**NOTE: Please be sure that the templates, rule sets and logs you provide as part of your bug report do not contain any sensitive information.**

**Expected behavior**

**Screenshots**

**Operating System:**
[eg, MacOS, Windows, Ubuntu, etc]

**OS Version**
[eg Catalina, 10, 18.04, etc]

**Additional context**

**Comment by nathanataws** [comment]
This looks like an empty ticket.  Please add details and reopen it if you need to.
