### ISSUE TITLE
[Enhancement] Compute rule validation/test elapsed time

### ISSUE THREAD

**Issue by fabiodouek** [aws-cloudformation/cloudformation-guard#338]
**Is your feature request related to a problem? Please describe.**

I'm currently running cfn-guard for a specifiec use case, where I validate thousands of resources across 10-20 rules. It runs almost 100k rule evaluations.

I've written a post processor to convert the cfn-guard json payload to Junit, and then I apply a transformation to generate HTML reports. All working well, except there is no evaluation elapsed time being returned by cfn-guard in the JSON Payload, so not getting these metrics in my reports at the moment.

**Describe the solution you'd like**

I would like elapsed time to be returned by cfn-guard for both evaluate and test modes, so it can be exposed in my reports, and also I can use to tune the validations whenever needed.

**Comment by joshfried-aws** [comment]
Hi @fabiodouek thanks for bringing this up, it's a great suggestion. We are tracking both this and #265. I consider this to be a pre-requisite for the standard reporter. We will update as we progress on the implementation. 

Thanks,

**Comment by joshfried-aws** [comment]
Hi @fabiodouek this has now been done for the JUnit reporting options for both validate and test. 

I am going to go ahead and close this out for now. Please feel free to reopen if necessary
