### ISSUE TITLE
[BUG] Hard to distinguish system errors from validation failures

### ISSUE THREAD

**Issue by fabiodouek** [aws-cloudformation/cloudformation-guard#344]
**Describe the bug**

When running cfn-guard validate with -o json command, if any of the evaluation rules fail, it returns exit code 5, which is fine. There is enough metadata in the JSON response to identify which rule(s) are non-compliant.

However, if there is a parsing error in one of the rules, the error message "Parsing error handling rule" is returned outside of the JSON payload, and the exit code is also 5.
Therefore it makes hard to find out that there is a critical system error.

**To Reproduce**
Please supply:

1. Example rules and template that results in the error: Any CFN template with at least one malformed rule.
2. The commands you used to invoke the tool: cfn-guard validate --rule <RULE_DIR> --data <CFN_DATA_DIR> -o json --show-summary all
3. The output: "Parsing error handling rule"

**Expected behavior**
I would expect either to receive an exit code that allows me to identify system error (other than 5), or a well-formed JSON payload with sufficient relevant metadata about the error.

**Operating System:**
Amazon Linux 2

**Comment by akshayrane** [comment]
Thanks @fabiodouek for highlighting this issue, we will evaluate the possibility of emitting different status codes in case of a system error vs the ones that result from user input.

**Comment by fabiodouek** [comment]
Hi @akshayrane , that would be great. Thanks for your prompt response.

**Comment by joshfried-aws** [comment]
Hi @fabiodouek, we have addressed this issue as part of #379. It will be included in our next release. 

As a result I will close this issue. Feel free to reopen if need be. 

Thanks,
