### ISSUE TITLE
[Feature Request]: Support for external json files as variables

### ISSUE THREAD

**Issue by kgrvamsi** [aws-cloudformation/cloudformation-guard#356]
**Describe the issue**

To support the intake for external file that could read json/yml files and support cfn guard rules for dynamic variables inside the rule.

**Any examples**

CFN Guard rules can have functionality to have utilities that can be used inside the rules.

utility.rs

```rust
use std::{
    fs::File,
    io::BufReader,
    path::Path,
    error::Error
};

use serde_json::Value;

fn read_variables_from_file<P: AsRef<Path>>(path: P) -> Result<Value, Box<dyn Error>> {
    // Open file in RO mode with buffer
    let file = File::open(path)?;
    let reader = BufReader::new(file);

    // Read the JSON contents of the file
    let u = serde_json::from_reader(reader)?;

    Ok(u)
}
```
variables.json

```json
{
    "names": [
        "nokia",
        "verizon",
        "att",
        "tmobile",
        "mint"
    ]
}
```

s3_bucket_naming_standard.guard

```shell
let json_file = read_variables_from_file("./variables.json")
rule s3_bucket_name_check when %s3_buckets !empty {
    %s3_buckets {
        Properties {
             # common prefix
             BucketName == /(^[ name IN %json_file.names ]-[a-zA-Z\.-]+)/ 
        }
    }
}
```
command line support 

```bash
cfn-guard validate -r ../cfn-rules/cloudformation/aws/s3/s3_bucket_naming_standard.guard --data cdk.out/*.template.json -v variables.json --show-summary all
```

**Operating System:**

MacOS 13.2.1

**OS Version**

Ventura

**Comment by joshfried-aws** [comment]
Hi @kgrvamsi 

guard does support additional input files via the ‘—input’ flag. You can repeat as many as you need  

thanks to @dchakrav-github for clearing this up for me. 

I am going to close this issue. Feel free to reopen if need be.
