### ISSUE TITLE
[GENERAL ISSUE] sam build fails due to certificate problem

### ISSUE THREAD

**Issue by polothy** [aws-cloudformation/cloudformation-guard#386]
**Describe the issue**

Was trying out the new `sam build` option and got this far:

```
❯ sam build --use-container
Starting Build inside a container
Building codeuri: /path/to/cloudformation-guard runtime: provided.al2 metadata: {'BuildMethod': 'makefile'} architecture: x86_64 functions: CloudFormationGuardLambda

Fetching public.ecr.aws/sam/build-provided.al2:latest-x86_64 Docker container image........................................................................................................................................................................................................................................................................................................................................................................................................................................................
Mounting /path/to/cloudformation-guard as /tmp/samcli/source:ro,delegated, inside runtime container

Build Failed
Running CustomMakeBuilder:CopySource
Running CustomMakeBuilder:MakeBuild
Current Artifacts Directory : /tmp/samcli/artifacts
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source /root/.cargo/env && rustup target add x86_64-unknown-linux-musl
Error: CustomMakeBuilder:MakeBuild - Make Failed: curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
/bin/sh: /root/.cargo/env: No such file or directory
make: *** [build-CloudFormationGuardLambda] Error 1
```

Looks like something is wrong with certs in the docker image. I can run curl on my computer and it works fine, EG this works:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs
```

**Operating System:**
MacOS

**OS Version**
13.4.1

**Comment by joshfried-aws** [comment]
Hi @polothy we were unable to reproduce this issue on our end. Is this issue still occurring for you? 

 ![image](https://github.com/aws-cloudformation/cloudformation-guard/assets/112121129/911aecdb-064c-4ffa-ac1a-9a5111525acd)

**Comment by joshfried-aws** [comment]
Hi @polothy we were unable to reproduce this issue locally. Would you mind attempting to reproduce it on your side again?

Thanks,

![image](https://github.com/aws-cloudformation/cloudformation-guard/assets/112121129/20ed2029-4c64-4c2d-a241-d9c826eb68ab)

**Comment by polothy** [comment]
Hello thanks for trying. Glad it's working for you, I'm still having the same error.  I'm on Intel Core i9 and Docker Desktop 4.22.1 (118664).

But, this seems like a "something is wrong with your environment" vs something wrong with the Guard project.

**Comment by joshfried-aws** [comment]
Hi @polothy have you tried downgrading docker version?

**Comment by joshfried-aws** [comment]
I'm going to close out this issue since as you reported it seems to be more an issue with your own environment. Please feel free to reopen if you think otherwise.

Thanks,
