### ISSUE TITLE
[BUG] Incorrect download URL for pre-built binary

### ISSUE THREAD

**Issue by tsamuel33** [aws-cloudformation/cloudformation-guard#391]
**Describe the bug**
When attempting to install cfn-guard using the pre-built binary via the install-guard.sh script, we receive a 404 error.

**To Reproduce**
Run the following command (running on ubuntu-latest GitHub Actions runner):
curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/aws-cloudformation/cloudformation-guard/main/install-guard.sh | sh

Output:
curl: (22) The requested URL returned error: 404
error attempting to download from the github repository
Error: Process completed with exit code 1.

**Expected behavior**
cfn-guard installs correctly

**Operating System:**
Ubuntu

**OS Version**
22.04

**Additional context**
Our workflows ran successfully this morning, but started failing on the installation step this afternoon. We believe the issue may be due to a recent commit in this repo: dd9edd1

This commit changed the download URL and appears to be missing "aws-cloudformation" in the URL (downloading from https://github.com/cloudformation-guard rather than https://github.com/aws-cloudformation/cloudformation-guard)

**Comment by joshfried-aws** [comment]
Hi @tsamuel33 thank you for bringing this to our attention. We are working on this immediately.
