### ISSUE TITLE
Simple regex seeking public CIDR not working

### ISSUE THREAD

**Issue by jnlkdzsb** [aws-cloudformation/cloudformation-guard#41]
Using the public website to evaluate rust regexp (https://rustexp.lpil.uk/), I found i could use "CidrIp":\s*"0\.0\.0\.0/0" to find public IP

But upon placing and then running tests against a security group, it rendered false positives

Test Case snippet of CFN
    "Resources": {
        "WebLoadBalancerSG": {
            "Type": "AWS::EC2::SecurityGroup",
            "Properties": {
                "VpcId": {
                    "Ref": "VPCid"
                },
                "GroupDescription": "WS Load Balancer Security Group",
                "Tags": [
                    {
                        "Key": "Environment",
                        "Value": {
                            "Ref": "Environment"
                        }
                    },
                    {
                        "Key": "Application",
                        "Value": {
                            "Ref": "Application"
                        }
                    },
                    {
                        "Key": "Vertical",
                        "Value": {
                            "Ref": "Vertical"
                        }
                    },
                    {
                        "Key": "Project",
                        "Value": {
                            "Ref": "Project"
                        }
                    }
                ],
                "SecurityGroupIngress": [
                    {
                        "IpProtocol": "tcp",
                        "FromPort": "80",
                        "ToPort": "80",
                        "CidrIp": "10.0.0.1/8"
                    },
                    {
                        "IpProtocol": "tcp",
                        "FromPort": "80",
                        "ToPort": "80",
                        "CidrIp": "192.168.0.0/16"
                    },
                    {
                        "IpProtocol": "tcp",
                        "FromPort": "443",
                        "ToPort": "443",
                        "CidrIp": "0.0.0.1/0"
                    },
                    {
                        "IpProtocol": "tcp",
                        "FromPort": "443",
                        "ToPort": "443",
                        "CidrIp": "192.168.0.0/16"
                    },
                    {
                        "IpProtocol": "tcp",
                        "FromPort": "3389",
                        "ToPort": "3389",
                        "CidrIp": "10.0.0.1/8"
                    },
                    {
                        "IpProtocol": "tcp",
                        "FromPort": "3389",
                        "ToPort": "3389",
                        "CidrIp": "192.168.0.0/16"
                    }
                ]
            }
        }
    },

Rule
AWS::EC2::SecurityGroup SecurityGroupIngress ==  /"CidrIp":"0\.0\.0\.0/0"/ << Publicly accessible Security Group

Produces, 
>cfn-guard --template fake.json --rule_set tt.txt
[WebLoadBalancerSG] failed because [SecurityGroupIngress] is [[{"CidrIp":"10.0.0.1/8","FromPort":"80","IpProtocol":"tcp","ToPort":"80"},{"CidrIp":"192.168.0.0/16","FromPort":"80","IpProtocol":"tcp","ToPort":"80"},{"CidrIp":"0.0.0.1/0","FromPort":"443","IpProtocol":"tcp","ToPort":"443"},{"CidrIp":"192.168.0.0/16","FromPort":"443","IpProtocol":"tcp","ToPort":"443"},{"CidrIp":"10.0.0.1/8","FromPort":"3389","IpProtocol":"tcp","ToPort":"3389"},{"CidrIp":"192.168.0.0/16","FromPort":"3389","IpProtocol":"tcp","ToPort":"3389"}]] and Publicly accessible Security Group
Number of failures: 1

**Comment by jnlkdzsb** [comment]
My bad.  it works fine but didn't realize that the logic should have been written differently to detect and report errors.

**Comment by nathanataws** [comment]
No worries! :-)
