### ISSUE TITLE
Add support for SARIF [Enhancement]

### ISSUE THREAD

**Issue by brianterry** [aws-cloudformation/cloudformation-guard#412]
**Is your feature request related to a problem? Please describe.**
As of today the output of the CLI and Lambda function does not support SARIF.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
SARIF (Static Analysis Results Interchange Format) is an OASIS Standard that defines an output file format. The SARIF standard is used to streamline how static analysis tools share their results. 

**Describe the solution you'd like**
I would like to have a option to output the scan result in SARIF so that it can be ingested into other systems.

**Comment by joshfried-aws** [comment]
Hi @brianterry thanks for the suggestion. We are going to track this and will keep this issue updated with any relevant details.

**Comment by dannyvassallo** [comment]
Hey @brianterry!  We've added SARIF output-format support to the validator command [here](https://github.com/aws-cloudformation/cloudformation-guard/pull/473). It will be available in the next release.
