### ISSUE TITLE
[GENERAL ISSUE] Documentation

### ISSUE THREAD

**Issue by GITOffMuhLawn** [aws-cloudformation/cloudformation-guard#414]
You don't actually have the regex rules/syntax posted anywhere.  At best everyone that uses it cobbles together what they have based on example rules or threads from issues/bugs but you don't actually have how you can use it spelled out anywhere and it's infuriating.  The documentation for this tool is keeping it's adoption from being wider than it should be.  It does not just simply use a passthrough the Rust regex because if it did I could should be able to do %resources.Properties.Tags[*].[Key ==  (?i)description] and it would filter regardless of the case sensitivity of the search but that doesn't work.  It's not explained anywhere.

**Comment by joshfried-aws** [comment]
Hi @GITOffMuhLawn thanks for the feedback. We are always open to looking into how we can better improve our documentation. I see that the way to handle regex is one of them. 

That said while guard in fact does not use a passthrough to the standard rust regex crate, it does use a passthrough to the fancy regex crate. Guard uses `/regex/` syntax to tell the engine that we're comparing against a regex pattern. 

That said, it's important to note that you have a syntax error here in your example. 

the following rule would pass 

```
let bucket = Resources.*[ type == "AWS::S3::Bucket" ]

%bucket !empty

let tag = %bucket.Properties.Tags[ key == /(?i)description/ ]

%tag !empty

```

using the following yaml file as a test file 

```yaml
Resources:
  bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      Tags:
        - Key: "DeScrIption"
          Value: "my_s3_bucket"
```

Hope this was sufficient. Please let me know if you'd like any further clarifications.

**Comment by joshfried-aws** [comment]
Hi, I'm going to assume the above answer was sufficient and will close this issue. 

Feel free to reopen if you require any further clarifications

Thanks,

**Comment by joshfried-aws** [comment]
@GITOffMuhLawn no problem. Appreciate the feedback here on ways we can improve our documentation whether that means adding more of it, or making it easier to understand.

Glad you were able to unblock yourself.
