### ISSUE TITLE
[Enhancement] Only show errors/failures in output

### ISSUE THREAD

**Issue by bestickley** [aws-cloudformation/cloudformation-guard#425]
**Is your feature request related to a problem? Please describe.**

It is annoying to have to comb through the output to find failures which is the only output I'm interested in.

**Describe the solution you'd like**

Please provide a way to customize the CLI to only show failures.

**Describe alternatives you've considered**

I've tried `--show-summary` but it does not solve my problem.

**Comment by joshfried-aws** [comment]
Hi @bestickley can you elaborate a bit on what the solution you're looking for would look like? I'm not sure I fully understand what you would like to see. By default cfn-guard only shows failures. Are you looking for something that doesn't provide snippets of the template where the failure occurred?

**Comment by bestickley** [comment]
@joshfried-aws, thanks for your response. I get hundreds of lines of:
```
Rule [SECRETSMANAGER_USING_CMK] is not applicable for template [manifest.json]
--
Evaluation of rules secretsmanager_using_cmk.guard against data telus-sh-app-stickb-AuthnMgmtApiStage.assets.json
--
Rule [SECRETSMANAGER_USING_CMK] is not applicable for template [telus-sh-app-stickb-AuthnMgmtApiStage.assets.json]
--
Evaluation of rules secretsmanager_using_cmk.guard against data tree.json
--
Rule [SECRETSMANAGER_USING_CMK] is not applicable for template [tree.json]
--
```
even when no failures.

**Comment by joshfried-aws** [comment]
Hi @bestickley which version of cfn-guard are you using?

**Comment by bestickley** [comment]
@joshfried-aws,
```bash
cfn-guard --version
cfn-guard 3.0.2
```

**Comment by dannyvassallo** [comment]
Hello @bestickley,

This has been fixed. Thank you for bringing this to our attention.

Closing the issue.
