### ISSUE TITLE
[BUG] cfn-guard-rulegen output is not consistent

### ISSUE THREAD

**Issue by chenrui333** [aws-cloudformation/cloudformation-guard#44]
**Describe the bug**
When I tried to use the tool to generate the ruleset, it is not consistent between the different runs.

**To Reproduce**
Please supply:

1. install cfn-guard-rulegen
2. run against `ebs-volume-template.json` in the repo

### first run

```
cfn-guard-rulegen ebs-volume-template.json
AWS::EC2::Volume AvailabilityZone == us-west-2b |OR| AWS::EC2::Volume AvailabilityZone == us-west-2c
AWS::EC2::Volume Encrypted == false
AWS::EC2::Volume Size == 99 |OR| AWS::EC2::Volume Size == 101
```

### second run

```
cfn-guard-rulegen ebs-volume-template.json
AWS::EC2::Volume Encrypted == false
AWS::EC2::Volume AvailabilityZone == us-west-2c |OR| AWS::EC2::Volume AvailabilityZone == us-west-2b
AWS::EC2::Volume Size == 99 |OR| AWS::EC2::Volume Size == 101
```

**NOTE: Please be sure that the templates, rule sets and logs you provide as part of your bug report do not contain any sensitive information.**

**Expected behavior**
Should always produce the same ruleset in order.

**Comment by nathanataws** [comment]
Good catch.  I'll see if we can make this deterministic.

**Comment by chenrui333** [comment]
@nathanataws thanks for the fix, I am curious why do you prefer to have `beta` in the release tag? Thanks!

**Comment by nathanataws** [comment]
That's our current convention.  That said, I know we need to remove it to get the binaries to build for homebrew. Before we can ship binaries, though, we need to finish our attribution document for the open source we're compiling in. From there, we'll move all the pieces around to get the builds going continuously. It shouldn't be too much longer.

**Comment by chenrui333** [comment]
Sounds good, thanks!
