### ISSUE TITLE
[BUG] remove beta identifier in the latest release tag?

### ISSUE THREAD

**Issue by chenrui333** [aws-cloudformation/cloudformation-guard#45]
While I am filing the homebrew formulae on [cfn-guard](https://github.com/Homebrew/homebrew-core/pull/58364) and [cfn-guard-rulegen](https://github.com/Homebrew/homebrew-core/pull/58366), I have run into a audit issue that the latest version tag has `beta` in it, I wonder if you folks can release a brand new regular version like `v0.5.2`. Thanks!

**Comment by nathanataws** [comment]
Hey, @chenrui333 !  Thanks for looking into this.  

We'll look at getting that taken off for 0.6.0 but it may have to wait for 1.0, unfortunately.  We'll see what we can do.

**Comment by chenrui333** [comment]
@nathanataws, I think a better and easy solution might be checkout a new branch from 0.5.2 tag and release a new tag?

This way, I can be unblocked to releasee it on the homebrew side.

Let me know if it makes sense or too much hassle. :)

**Comment by chenrui333** [comment]
> Hey, @chenrui333 ! Thanks for looking into this.
> 
> We'll look at getting that taken off for 0.6.0 but it may have to wait for 1.0, unfortunately. We'll see what we can do.

I saw you are going to fix the deterministic output, maybe we can address the release tag semantics per that release? :)

**Comment by jotompki** [comment]
This tag has been removed or 0.7.0. Only encountered this issue when I tried  to do the same thing as you [publishing a formula](https://github.com/Homebrew/homebrew-core/pull/61550) 👍
