### ISSUE TITLE
license conflicts with license header

### ISSUE THREAD

**Issue by kapilt** [aws-cloudformation/cloudformation-guard#47]
**Describe the bug**
The repo has an apache 2.0 license, but the file headers has content that is not standard apache pre-amble and its unclear if its even related to opensource vs some contractual agreement executed on a party to party basis.

"This AWS Content is provided subject to the terms of the AWS Customer Agreement available at http://aws.amazon.com/agreement or other written agreement between Customer and either Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both."

**Comment by nathanataws** [comment]
Thanks for bringing that to our attention!  I'll check with the legal side and make sure we don't have wires crossed here.

**Comment by nathanataws** [comment]
Haven't forgotten about this.  Should have an answer soon.
