### ISSUE TITLE
[BUG] "true" does not equal true

### ISSUE THREAD

**Issue by jkruse14** [aws-cloudformation/cloudformation-guard#491]
**Describe the bug**
When running guard as a lambda, the lambda parses boolean values from the input cloudformation resource as strings rather than as a boolean. I have this running as CloudFormation Hook. The Hook lambda gets the resource properties as a JSONObject (Java) stringified and sends it to the Guard lambda with the associated rules. The resource properties looks like this:

```
{
    "resourceProperties": {
        "PublicAccessBlockConfiguration": {
            "RestrictPublicBuckets": "true",
            "IgnorePublicAcls": "true",
            "BlockPublicPolicy": "true",
            "BlockPublicAcls": "true"
        },
        "BucketName": "bucket-name",
        "LoggingConfiguration": {
            "DestinationBucketName": "common-logging",
            "LogFilePrefix": "s3/bucket-name"
        }
    }
}
```
When the rules run, I get the following error:

<img width="557" alt="image" src="https://github.com/aws-cloudformation/cloudformation-guard/assets/16331726/8c95cf27-cf4d-4fea-bb41-8f58ef78cc58">

When CloudFormation specifies that a value is a boolean, it does accept `"true"`. Because this is an existing pattern in CloudFormation and Guard is meant to follow CloudFormation, I would like to request that the boolean values `true` and `false` have equality with the string value `"true"` and `"false"`, respectively.

**To Reproduce**
version:
```
$ cfn-guard --version
cfn-guard 3.0.3
```
Commands:
```bash
S3_DATA="{\\\"Resources\\\":{\\\"PublicAccessNotBlocked\\\":{\\\"Type\\\":\\\"AWS::S3::Bucket\\\",\\\"Properties\\\":{\\\"PublicAccessBlockConfiguration\\\":{\\\"RestrictPublicBuckets\\\":\\\"true\\\",\\\"IgnorePublicAcls\\\":\\\"true\\\",\\\"BlockPublicPolicy\\\":\\\"true\\\",\\\"BlockPublicAcls\\\":\\\"true\\\"},\\\"BucketName\\\":\\\"cfn-guard-test-507687777964-us-east-1\\\"}}}}"
S3_RULES="let buckets = Resources.*[ Type == 'AWS::S3::Bucket' ]\nlet bucketPolicies = Resources.*[ Type == 'AWS::S3::BuckePolicy' ]\nwhen %buckets !empty {\n  %buckets {\n  Properties {\n  PublicAccessBlockConfiguration {\n  BlockPublicAcls == true\n  <<\n          result: NON_COMPLIANT\n          message: BlockPublicAcls must be set to true\n  >>\n  BlockPublicPolicy == true\n  <<\n          result: NON_COMPLIANT\n          message: BlockPublicPolicy must be set to true\n  >>\n  IgnorePublicAcls == true\n  <<\n          result: NON_COMPLIANT\n          message: IgnorePublicAcls must be set to true\n  >>\n  RestrictPublicBuckets == true\n  <<\n  result: NON_COMPLIANT\n          message: RestrictPublicBuckets must be set to true\n  >>\n  }\n   }\n  }\n  }\n}"

aws lambda invoke \
--profile $PROFILE \
--function-name cfn-guard \
--cli-binary-format raw-in-base64-out \
--payload "{\"data\":\"${S3_DATA}\",\"rules\":[\"${S3_RULES}\"]}" \
output.json
```

**Expected behavior**
`"true" == true` resolves in an equality match
`"false" == false` resolves in an equality match

**Additional context**
Run via lambda

**Comment by joshfried-aws** [comment]
Hi @jkruse14, first of all I would like to say that this is certainly not to be considered a bug. This is absolutely expected behaviour as our current spec. Second, I'm not sure I agree with this. We already provide ways for users to convert [booleans to strings,](https://github.com/aws-cloudformation/cloudformation-guard/blob/main/docs/FUNCTIONS.md#parse_string) and [vice versa](https://github.com/aws-cloudformation/cloudformation-guard/blob/main/docs/FUNCTIONS.md#parse_boolean) using our converter functions. I personally believe this to be a slippery slope when it comes to allowing equalities between different data types. 

It's also important to note that although CloudFormation is in the name, cfn-guard is still considered to be a generic tool.

**Comment by jkruse14** [comment]
> Hi @jkruse14, first of all I would like to say that this is certainly not to be considered a bug. This is absolutely expected behaviour as our current spec. Second, I'm not sure I agree with this. We already provide ways for users to convert [booleans to strings,](https://github.com/aws-cloudformation/cloudformation-guard/blob/main/docs/FUNCTIONS.md#parse_string) and [vice versa](https://github.com/aws-cloudformation/cloudformation-guard/blob/main/docs/FUNCTIONS.md#parse_boolean) using our converter functions. I personally believe this to be a slippery slope when it comes to allowing equalities between different data types.
> 
> It's also important to note that although CloudFormation is in the name, cfn-guard is still considered to be a generic tool.

Thanks for the explanation @joshfried-aws! That makes sense and I had completely missed the `parse_*` functions. I'm closing this issues.
