### ISSUE TITLE
Create new forms for the inverse of the current wildcards

### ISSUE THREAD

**Issue by nathanataws** [aws-cloudformation/cloudformation-guard#5]
In other words, where

`AWS::IAM::Role AssumeRolePolicyDocument.Statement.*.Principal.Service.* == lambda.amazonaws.com`

means *"At least one item that matches those wildcards should match that value“*

and 

`AWS::IAM::Role AssumeRolePolicyDocument.Statement.*.Principal.Service.* != lambda.amazonaws.com`

means *"None of the items that those wildcards match should match that value“*

Customers have some use cases where a wildcard syntax that’s equivalent to *“All wildcards must match this value”* would be very useful.

For example: if customers want the ability to ensure only whitelisted services are included in the trust policy. The only allowed values are specified in a list. 

`AWS::IAM::Role AssumeRolePolicyDocument.Statement.*.Principal.Service.* ONLY_IN ["lambda.amazonaws.com","ec2.amazonaws.com"]`

means “*All items must match a value in the list*”

And if they really want to make sure every wildcarded item only matches an exact value, we could add something like:

`AWS::IAM::Role AssumeRolePolicyDocument.Statement.*.Principal.Service.* ONLY lambda.amazon`

**Comment by dchakrav-github** [comment]
Guard 2.0 supports this semantic with the use of SOME keyword to match at least one, and default to match ALL. The semantic is consistent regardless of the type of comparison `==`, `!=`, `iN` and others.
