### ISSUE TITLE
Looking for help: S3 Bucket Policy

### ISSUE THREAD

**Issue by TheFlexican** [aws-cloudformation/cloudformation-guard#58]
Hi,

Looking for some help. 
Trying to setup cfn-guard to parse S3 BucketPolicy to disallow public write. Is cfn-guard able to parse the S3 BucketPolicy, looking for s3:pubobject or s3:* on principal: "*" ? 

I tried playing with regex and json in the ruleset file, but I can't get it to work. Any help is appreciated.

Thank you.

**Comment by TheFlexican** [comment]
I played around a bit more, and I came to the following solution.

AWS::S3::BucketPolicy WHEN PolicyDocument.Statement.*.Principal == * check PolicyDocument.Statement.*.Action != /(?i)\b(S3:PutObject)\b|(?i)(S3:\*)/

The thing I'm facing now is, there could be a use-case to actually have principal * and for example s3:PutObject, but have a condition that specifies a more granular restriction to who can access the bucket. Can you see a way to implement that into this rule?

**Comment by nathanataws** [comment]
I keep trying to write out different approaches but I don't think I can say anything useful without more context.  

Do you have an example cfn template to check for that condition that we can kick around?

**Comment by TheFlexican** [comment]
Hi,

Here is a snippet, containing a condition, to allow only our own organization to access this bucket.

  DummyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DummyS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - "s3:*"
            Resource:
              - !Sub "arn:aws:s3:::${DummyS3Bucket}"
              - !Sub "arn:aws:s3:::${DummyS3Bucket}/*"
            Condition:
              StringEquals:
                aws:PrincipalOrgId: "some-org-id"

So I would like to write a rule, that checks for principal *, if it finds it, it checks the action if its either s3:pubobject or s3:*. When both rules are satisfied, then it should check if there is some condition specified. It doesn't have to parse the condition, but for now just checking if there is a condition would help me out a lot.

Thank you.

**Comment by nathanataws** [comment]
Try a mix of predicate (ie, true/false) checks and regexes like:
```
AWS::S3::BucketPolicy PolicyDocument.Principal != * |OR| AWS::S3BucketPolicy when PolicyDocument.Statement.Action in [s3:pubobject, s3:start] check PolicyDocument.Statement = /.*Condition.*/
```

**Comment by jotompki** [comment]
Our new proposal for rule blocks #111 and filtering enhancements #115 should allow you to craft a complex check like this. You can refer to named rules to simplify this check.



Example ruleset from the new version of the language that u (still in development): 
```
rule disallow_public_write_s3_policy {
    AWS::S3::BucketPolicy {
        let permissive_statements = Properties.PolicyDocument.Statement[ Principal == "*"]
        %permissive_statements.Action[*] !=  /s3:PutObject|s3:\*/
    }
}
```

**Comment by dchakrav-github** [comment]
In Guard 2.0 this can be expressed as 

```
AWS::S3::BucketPolicy Properties {
    PolicyDocument.Statement[*] {
        WHEN SOME Principal[*]  == '*' 
             SOME Action[*]     == /s3:Put*|s3:\*/ OR
                  Action[*]     == '*'
        {
            Condition.*[ 'aws:PrincipalOrgId' EXISTS ] !EMPTY
        }
    }
}
```

The rule states for all `AWS::S3::BucketPolicy` configured in a template, ensure that for ALL `Statement` inside `PolicyDocument` if a Statement matches **at-least-one** `SOME Principal == '*'` and **at-least-one**   `SOME Action[*]     == /s3:Put*|s3:*|\*/ OR Action[*] == '*'` [matching '*' by itself with Regex gets tricky hence the split] then ensure that a `Condition` has one entry with `aws:PrincipalOrgId`

Attached Guard file, unit tests and validation files
[s3-bucket-policy.zip](https://github.com/aws-cloudformation/cloudformation-guard/files/6511396/s3-bucket-policy.zip)

**Comment by dchakrav-github** [comment]
Attaching correct files
[s3-bucket-policy.zip](https://github.com/aws-cloudformation/cloudformation-guard/files/6511453/s3-bucket-policy.zip)

**Comment by dchakrav-github** [comment]
@TheFlexican please re-open this issue if you needed further clarification. The updated zip file has the complete example with tests and the same provided here
