### ISSUE TITLE
Create syntax to allow for Rule Sets to be imported into other Rule Sets

### ISSUE THREAD

**Issue by nathanataws** [aws-cloudformation/cloudformation-guard#6]
... and have the rule sets be concatenated together. 

`import <filename>`

(We would obviously need to check for - and error on - circular dependencies when importing.)

**Comment by iahmad6** [comment]
Are you working on this currently? Also, what does it mean when an issue has a release tag?

**Comment by nathanataws** [comment]
I can't say if work has started on it yet.  But the release tag is our best guess on when it will go out.

**Comment by razcloud** [comment]
Hi @iahmad6,

Are you still interested in this capability?  If so, would you like for a complete import of another complete ruleset file, or the ability to import a subset of rules from that file?

**Comment by razcloud** [comment]
Closing, please re-open if needed.
