### ISSUE TITLE
[Enhancement] Run cfn-guard check without parameters

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-guard#62]
**Is your feature request related to a problem? Please describe.**
Currently you always have to specify both the ruleset and the templates. This makes scanning mulitple templates in one source code repository, or templates across different repositories difficult (see also #22 )
 
**Describe the solution you'd like**
Having a default filename for the rules and allowing a list of templates as input, would make it a lot easier to run. eg.

```
cfn-guard check template1.yaml template2.yaml
cfn-guard check template*.yaml
cfn-guard check --rule_set non-default-rules *.yaml
```

**Comment by ldomb** [comment]
Would be great to be able to point to multiple rules as well in the same command.

**Comment by benbridts** [comment]
Can we reopen this? @shreyasdamle 

Not being able to pass multiple files makes it so much harder to integrate this in a repository
