### ISSUE TITLE
[Enhancement] Publish to crates.io via travisci

### ISSUE THREAD

**Issue by jotompki** [aws-cloudformation/cloudformation-guard#68]
Uploading to crates.io from desktop is error prone. We need a step in our deployment script on travis to do this for each package automatically. Since there are multiple crates in this repo, we need something a bit more sophisticated than just running from the root. Additionally, it would nice to keep a common versioning for all the tools as cfn-guard depends on rulegen and the lambdas depend on their respective tools as well.

**Comment by akshayrane** [comment]
Since this is a process improvement for the deployment/release of Guard to crates.io and it does not directly affect customer experience, we will track this issue internally.
