### ISSUE TITLE
[Enhancement] Recursive scanning of templates in a folder

### ISSUE THREAD

**Issue by Rishwanth29** [aws-cloudformation/cloudformation-guard#79]
I am working on an usecase where I need to scan multiple cft files (yaml or json) against the rules.
But after reading the documentation on the cfn-guard I came to know that its an 1:1 validation, is there any way that i can do it recursively?

**Comment by ikben** [comment]
See also: https://github.com/aws-cloudformation/cloudformation-guard/issues/62

**Comment by jkuek** [comment]
I'm wanting to use cfn-guard in a build pipeline and lack of support to scan multiple files is an issue.

Here's the workaround I'm using at present (Powershell):

`Get-ChildItem -recurse *.yaml,*.yml -exclude azure-pipelines.yml | % { Write-Host running cfn-guard check on $_.FullName; cfn-guard-linux/cfn-guard check -t $_.FullName -r security_rules.ruleset }`

However, this has issues as it only returns an error (non-zero) if the last file fails validation.

Ideally what I would like is to run cfn-guard recursively over my templates, with the option to exclude in a certain folder or files matching a certain expression/name.

**Comment by 0xjjoyy** [comment]
Also looking to scan multiple CloudFormation template files. The use case would be to check all templates synthesized by CDK. The templates can be in nested directories in the cdk.out directory, so either some type of recursion or nested directory support.

**Comment by benbridts** [comment]
Folders can be passed to Guard version 2

**Comment by gandhek** [comment]
@Rishwanth29, this can be achieved in 2.0. You can find the relevant documentation [here](https://github.com/aws-cloudformation/cloudformation-guard/blob/main/docs/COMPLEX_COMPOSITION.md#validating-multiple-rules-against-multiple-data-files)
