### ISSUE TITLE
[Enhancement] Add rules to block entire Resource/Service.

### ISSUE THREAD

**Issue by doronvoerman** [aws-cloudformation/cloudformation-guard#81]
**Is your feature request related to a problem? Please describe.**
In our team we manage our AWS implementation and we don't want our developers to deploy certain services/resources. We want to use cfn-guard for this, to give quick feedback to our devs. However, we don't have the possibility to block an entire resource in Cloudformation (I'll use EC2 as an example) through cfn-guard.

**Describe the solution you'd like**
I want to be able to have a rule like `AWS::EC2 == false`.

**Describe alternatives you've considered**
As an alternative, we've worked with rules like `AWS:: EC2::Instance InstanceType == false`. This works, but does not give the proper feedback, and is more of a workaround.

**Comment by PatMyron** [comment]
tracking in https://github.com/aws-cloudformation/cloudformation-guard/issues/3
