### ISSUE TITLE
[Enhancement] Add a way to enforce encryption of EC2 instances in Block mappings

### ISSUE THREAD

**Issue by vennemp** [aws-cloudformation/cloudformation-guard#89]
Maybe it is already supported and I just haven't configured it properly but is there a way to enforce encryption of volumes declared as in the block device mappings of an ec2 instance?

I tried this but assume it is because BlockDeviceMappings is a list object so it would need to iterate over every entry in list.  

I didn't see an example of the syntax if it was supported.  If it is not supported, can this be added to the roadmap?
```
AWS::EC2::Instance == BlockDeviceMappings.Ebs.Encrypted == true
```
I could always use the aws::ec2::volumeattachment resource after creating the volume but it would not fix the problem for the root volume

**Comment by jotompki** [comment]
Since BlockDeviceMapping expects a list, you'd need to utilize the wildcard operator to enforce every member of the list to have encryption enabled:

```
AWS::EC2::Instance BlockDeviceMappings.*.Ebs.Encrypted == true
```

**Comment by vennemp** [comment]
I assumed it was something like that THANK YOU.
