### ISSUE TITLE
[Enhancement] Check rules organization wide through aws cloudformation service

### ISSUE THREAD

**Issue by philipbarwi** [aws-cloudformation/cloudformation-guard#90]
**Is your feature request related to a problem? Please describe.**
As a security engineer i want to be able to check/enforce the template during rollout in cloudformation organization wide - it's like a scp just for aws resources instead of iam actions.

**Describe the solution you'd like**
I want to be able to put one or more rules/configurations into cloudformation services which will be applied to cloudformation organizationwide.

**Describe alternatives you've considered**
Alternatives are aws config, but using aws config the misconfigured resources are only detected after creation, that would be different with org wide cfn-guard.

**Additional context**
///

**Comment by talkncloud** [comment]
I think the intention is that you push your IaC through CI/CD, cfn-guard would be a gate **before** deployment to check the template against your ruleset. If you that fails the deployment fails, or however you want to configure that.

**Comment by razcloud** [comment]
Hi @philipbarwi,

This requirement is out of scope of Guard itself, since Guard is a Policy as Code enforcement DSL and engine.  This request is more aligned to IaC and implementation via CI/CD.

**Comment by PatMyron** [comment]
think this could be achieved with a [hook](https://aws.amazon.com/blogs/mt/proactively-keep-resources-secure-and-compliant-with-aws-cloudformation-hooks/), similar to https://github.com/StyraInc/opa-aws-cloudformation-hook
