### ISSUE TITLE
[Enhancement] Check for high level AWS CFN resource 

### ISSUE THREAD

**Issue by n1t1nv3rma** [aws-cloudformation/cloudformation-guard#94]
**Is your feature request related to a problem? Please describe.**
- As security in-charge I want to make sure that users are not able to create any IAM related resource via CFN automation or my CICD pipeline.

**Describe the solution you'd like**
- I should be able to simply check if any AWS::IAM:* resource is available in the CFN template and fail. 

**Describe alternatives you've considered**
- I have to add every single IAM related CFN resource in the ruleset, and update my ruleset when a new AWS::IAM:* resource is available in CFN.

**Additional context**
- None

**Comment by jotompki** [comment]
Closing out as a duplicate of #3. Tracking there
