### ISSUE TITLE
[Enhancement] Document the rule syntax and allowed operators

### ISSUE THREAD

**Issue by jmnarloch** [aws-cloudformation/cloudformation-guard#95]
**Is your feature request related to a problem? Please describe.**
Currently the documentation is lacking the explanation what are the allowed operators of rules, as a first time user I need guess those or read that from the code directly.

**Describe the solution you'd like**
Document the rule syntax and flesh out all of the supported operators.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by PatMyron** [comment]
[ruleset syntax is described here](https://github.com/aws-cloudformation/cloudformation-guard/tree/master/cfn-guard#writing-rules)

**Comment by jotompki** [comment]
In addition, this [grammar](https://github.com/aws-cloudformation/cloudformation-guard/blob/master/GRAMMAR.md) defines all valid rulesets and can be used to determine if a ruleset is valid.
