### ISSUE TITLE
[Enhancement] Allow to enforce the property is set.

### ISSUE THREAD

**Issue by jmnarloch** [aws-cloudformation/cloudformation-guard#98]
**Is your feature request related to a problem? Please describe.**
I am trying to figure out what is they way to specify in ruleset that given property is set in template. 

**Describe the solution you'd like**
The use case that I am trying to address is that I want enforce enabling the encryption across CFN resources. There are simple cases like for instance [AWS::DynamoDB::Table](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html) in which the rule can be as simple as:

```
AWS::DynamoDB::Table SSESpecification == {"SSEEnabled":true}
```

but in case of SQS or SNS the configuration requires specifying a `KmsMasterKeyId` property.

```
AWS::SQS::Queue KmsMasterKeyId = ...
```

In this case I am more interested in enforcing that the setting has a value override rather then specific value that had been assigned. The reason for that is that the ruleset itself would be intended to be run across multiple templates across team/org.

Proposed syntax could be:

```
AWS::SQS::Queue KmsMasterKeyId == *
```

or 

```
AWS::SQS::Queue KmsMasterKeyId != null
```

or 

```
AWS::SQS::Queue KmsMasterKeyId exists
```

**Describe alternatives you've considered**
It appears that currently there is no way to enforce an attribute had been specified in template.

**Additional context**
N/A

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cloudformation-guard/issues/16

**Comment by jotompki** [comment]
This will be more explicitly possible in our next release detailed in #115. users can use `null` or `EXISTS` to check if properties are set as you suggested above.

**Comment by dchakrav-github** [comment]
With Guard 2.0 we have explicit `EXISTS` for this purpose. You can do 

```
AWS::SQS::Queue KmsMasterKeyId EXISTS
```
We recommend using the block syntax for more succinct checks e.g. 

```
AWS::SQS::Queue Properties {
     KmsMasterKeyId EXISTS
     Tags !EMPTY
     DelaySeconds IN r[60, 250) 
}
``` 
[sqs.zip](https://github.com/aws-cloudformation/cloudformation-guard/files/6505894/sqs.zip)

**Comment by dchakrav-github** [comment]
Let us know if you needed any other input
