### ISSUE TITLE
[Enhancement] Allow to substitute the resource name in the rule evaluation.

### ISSUE THREAD

**Issue by jmnarloch** [aws-cloudformation/cloudformation-guard#99]
**Is your feature request related to a problem? Please describe.**
There are case in which it would be useful to be able to reference the resource name in the given rule. An example could be a IAM Policy that disables the HTTP access to S3 bucket.

```
AWS::S3::BucketPolicy PolicyDocument == {"Statement":[{"Action":"*","Condition":{"Bool":{"aws:SecureTransport":"false"}},"Effect":"Deny","Principal":"*","Resource": "arn:aws:s3:::${AWS::ResourceName}/*"}]}
```

As in this particular case the policy Resource attribute requires to specify the resource name, though arguably it could had been replaced with wildcard `*` instead.

Note: `${AWS::ResourceName}` placeholder is pseudo attribute, as it's not even supported by CFN itself, a better name could be proposed to be used instead.

**Describe the solution you'd like**
Be able to reference a CFN resource name in the rule evaluation.

**Describe alternatives you've considered**
Remove the actual reference to the resource and use wildcard instead, though I can easily imagine use cases in which wildcard might not be ideal as well.

**Additional context**

**Comment by jotompki** [comment]
In #115, we allow for certain filtering and property access enhancements. One of these enhancements allows for assigning variables from incoming template. For example, one could check against the bucket name for an s3 bucket if present (2.0 rule language snippet in development):
```
rule substitute_s3_bucket_name {
    AWS::S3::BucketPolicy {
        let bucket_name = Properties.Name
        # checks that the resource conforms to a certain regex AND that the bucket name is in the regex
        Properties.PolicyDocument.Statement[*].Resource == /bucketnameregex/
        %bucket_name IN Properties.PolicyDocument.Statement[*].Resource 
    }
}
```

**Comment by benbridts** [comment]
To avoid confusion, the property is called  `Bucket` on the BucketPolicy:

```
rule substitute_s3_bucket_name {
    AWS::S3::BucketPolicy {
        let bucket_name = Properties.Bucket
        # checks that the resource conforms to a certain regex AND that the bucket name is in the regex
        Properties.PolicyDocument.Statement[*].Resource == /bucketnameregex/
        %bucket_name IN Properties.PolicyDocument.Statement[*].Resource 
    }
}
```

And I'm afraid that this won't work if you use a !Ref ?

(the `*` suggestion won't work either IIRC, as that will be rejected by S3)

**Comment by dchakrav-github** [comment]
benbridts@ and  jmnarloch@ Can we elaborate a bit more on what aspect did we need to check here? Are we looking for Bucket Policy containing `{ "Ref": "MyS3bucket" }` in where `MyS3Bucket` is defined in the template as well? Guard 2.0 does have support for following `Ref` but it would useful to understand this more.

**Comment by benbridts** [comment]
@dchakrav-github I think Resolving a Ref was the original question, my comment was only here to give John the chance to edit his comment.

**Comment by jmnarloch** [comment]
@dchakrav-github

The use case was that I would like to validate that a certain policy had been setup on the S3 bucket. In this particular case a policy for rejecting a HTTP access to S3 bucket.

This problem itself could be potentially solve in many ways and one of which could had been some form of `meta` checks like `HTTPSOnly: true`. In this idea the CFN-Guard would have the logic to understand the policies and check if one that disables HTTP access had been added.

But that aside the most straightforward way for verifying it is by exactly matching the PolicyDocument content. 

From the example above I could simplify it and change both the policy itself as well as condition to accept a wildcard.

```
{"Statement":[{"Action":"*","Condition":{"Bool":{"aws:SecureTransport":"false"}},"Effect":"Deny","Principal":"*","Resource": "arn:aws:s3:::*"}]}
```

Though in case I would like to specify a very explicit condition that has the exact bucket name I would like to have that defined as general CFN Rule. Because of that I would like to be able to reference the exact resource name in the pattern

```
{"Statement":[{"Action":"*","Condition":{"Bool":{"aws:SecureTransport":"false"}},"Effect":"Deny","Principal":"*","Resource": "arn:aws:s3:::{Ref: BucketName}"}]}
```

As proposed above. If the https://github.com/aws-cloudformation/cloudformation-guard/pull/115 solves this use case then feel free to resolve this ticket.

**Comment by priyap286** [comment]
@jmnarloch, I think you will find your answer in the comment of #186 . Closing this issue as I believe #186 answers your question. Please reopen this issue if you think it was closed in error.
